KeyPalette/additional_read_functions.h File Reference
Functions
DOUBLEVECTOR * read_doublearray_from_string (char *argument, char *delimiters, int max_numbers, short print)
LONGVECTOR * read_longarray_from_string (char *argument, char *delimiters, int max_numbers, short print)
Function Documentation
DOUBLEVECTOR* read_doublearray_from_string (char * argument, char * delimiters, int max_numbers, short print)
Definition at line 35 of file additional_read_functions.c.
References free_doublevector(), new_doublevector(), and DOUBLEVECTOR::nl.
LONGVECTOR* read_longarray_from_string (char * argument, char * delimiters, int max_numbers, short print)
Definition at line 93 of file additional_read_functions.c.
References free_longvector(), new_longvector(), and LONGVECTOR::nl.
Referenced by get_line(), and get_polygon().