Boussinesq/b_sources.c File Reference
#include `turtle.h`
*
#include `t_alloc.h`
*
#include `t_io.h`
*
#include `t_datamanipulation.h`
*
#include `t_utilities.h`
*
#include `rw_maps.h`
*
#include `geometry.h`
*
#include `g_raster2plvector.h`
*
#include `bigcells2.h`
*
#include `geometry2.h`
*
#include `b_utilities.h`
*
#include `b_solver.h`
*
#include `b_volumes.h`
*
#include `doublevector_utilities.h`
*
#include `preconditioned_conjugate_gradient.h`
*
#include `keywords_file_b.h`
*
#include `b_sources.h`
*
Functions
int get_sources (double t, DOUBLEVECTOR *sources)
S_TIMES * get_s_times (char *filename, short print)
void free_s_times (S_TIMES *s_t)
int get_dirichletsnode (double t, DOUBLEVECTOR *dirichlet)
Variables
STRINGBIN * filenames
DOUBLESQUARE_GRID * dsq
DOUBLE_GRID * dgrid
DOUBLERASTER_MAP * draster
PARAM * param
FLAG * flag
DOUBLEVECTOR * elevation_bottom_fine
DOUBLEVECTOR * elevation_bottom_coarse
DOUBLEVECTOR * elevation_bottom_flines
DOUBLEVECTOR * elevation_bottom_bottom
DOUBLEVECTOR * porosity_fine
DOUBLEVECTOR * water_surface_elevation
DOUBLEVECTOR * water_mass_error
S_TIMES * s_times
S_TIMES * dirichlet_times
Detailed Description
Author
Emanuele Cordano
Attention
This file is part of Boussinesq.
Boussinesq is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Boussinesq is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Boussinesq. If not, see http://www.gnu.org/licenses/.
Definition in file b_sources.c.
Function Documentation
void free_s_times (S_TIMES * s_t)
Author
Emanuele Cordano
Date
29 May 2008
Definition at line 166 of file b_sources.c.
References free_doublevector(), free_stringbin(), S_TIMES::s_suffixes, and S_TIMES::times.
Referenced by time_loop().
int get_dirichletsnode (double t, DOUBLEVECTOR * dirichlet)
Author
Emanuele Cordano
Date
May 2009
Parameters
t (double) time;
dirichlet_node map - (DOUBLEVECTOR *) dirichlet
Definition at line 182 of file b_sources.c.
References A_FLAG, DOUBLESQUARE_GRID::big, DOUBLERASTER_MAP::coarse, copy_doublevector(), DTM_MASK, PARAM::exp_dirichlet, free_doublevector(), I_DIRICHLETMAPSERIES_COARSE, SQUARE_GRID::indices_pixel, join_strings(), RASTER_MAP::layer, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, PARAM::null_dirichlet, read_doublevector_from_raster(), S_TIMES::s_suffixes, S_TIMES::times, and RASTER_MAP::UV.
Referenced by time_loop().
S_TIMES* get_s_times (char * filename, short print)
Author
Emanuele Cordano
Date
29 May 2009
Parameters
filename (char *)
print (short)
Definition at line 127 of file b_sources.c.
References st::index, LONGVECTOR::nh, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, read_doublearray(), read_index(), read_stringarray(), S_TIMES::s_suffixes, t_error(), t_fclose(), t_fopen(), and S_TIMES::times.
Referenced by time_loop().
int get_sources (double t, DOUBLEVECTOR * sources)
Author
Emanuele Cordano
Date
May 2009
Parameters
t (double) time;
sources - (DOUBLEVECTOR *) sources
Definition at line 67 of file b_sources.c.
References A_FLAG, DOUBLESQUARE_GRID::big, DOUBLERASTER_MAP::coarse, copy_doublevector(), DTM_MASK, free_doublevector(), I_SOURCEMAPSERIES_COARSE, SQUARE_GRID::indices_pixel, join_strings(), RASTER_MAP::layer, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, read_doublevector_from_raster(), S_TIMES::s_suffixes, S_TIMES::times, and RASTER_MAP::UV.
Referenced by time_loop().
Variable Documentation
DOUBLE_GRID* dgrid
Definition at line 126 of file main.c.
S_TIMES * dirichlet_times
Definition at line 72 of file b_solver.c.
DOUBLERASTER_MAP* draster
Definition at line 128 of file main.c.
DOUBLESQUARE_GRID* dsq
Definition at line 125 of file main.c.
DOUBLEVECTOR* elevation_bottom_bottom
map of the bottom elevation defined in the lines of the fine grid
Definition at line 134 of file main.c.
DOUBLEVECTOR* elevation_bottom_coarse
map of the bottom elevation (fine grid)
Definition at line 132 of file main.c.
DOUBLEVECTOR* elevation_bottom_fine
Definition at line 131 of file main.c.
DOUBLEVECTOR* elevation_bottom_flines
map of the bottom elevation (coarse grid)
Definition at line 133 of file main.c.
STRINGBIN* filenames
Definition at line 124 of file main.c.
FLAG* flag
Definition at line 149 of file main.c.
PARAM* param
coefficient F1 for surface flow as reported in Casulli,2008
Definition at line 148 of file main.c.
DOUBLEVECTOR* porosity_fine
map of the elvetion of the bottom of he coarse cells
map of the surface terrain elevation (fine grid lines)
Definition at line 137 of file main.c.
S_TIMES* s_times
map of instantaneous water mass error
eta_v and sources and dirichlet are defined as a global value, t_diagonal is the diagonal of t_st_element tensor
Definition at line 72 of file b_solver.c.
DOUBLEVECTOR* water_mass_error
map of instantaneous water surface on the pixels of the coarse grid
Definition at line 143 of file main.c.
DOUBLEVECTOR* water_surface_elevation
map of porosity defined on the pixels of the fine grid
Definition at line 142 of file main.c.