Boussinesq/b_sources.h File Reference
Data Structures
struct S_TIMES
Functions
S_TIMES * get_s_times (char *filename, short print)
void free_s_times (S_TIMES *s_t)
int get_sources (double t, DOUBLEVECTOR *sources)
int get_dirichletsnode (double t, DOUBLEVECTOR *dirichlet)
Detailed Description
Author
Emanuele Cordano
Attention
This file is part of Boussinesq.
Boussinesq is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Boussinesq is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Boussinesq. If not, see http://www.gnu.org/licenses/.
Definition in file b_sources.h.
Function Documentation
void free_s_times (S_TIMES * s_t)
Author
Emanuele Cordano
Date
29 May 2008
Definition at line 166 of file b_sources.c.
References free_doublevector(), free_stringbin(), S_TIMES::s_suffixes, and S_TIMES::times.
Referenced by time_loop().
int get_dirichletsnode (double t, DOUBLEVECTOR * dirichlet)
Author
Emanuele Cordano
Date
May 2009
Parameters
t (double) time;
dirichlet_node map - (DOUBLEVECTOR *) dirichlet
Definition at line 182 of file b_sources.c.
References A_FLAG, DOUBLESQUARE_GRID::big, DOUBLERASTER_MAP::coarse, copy_doublevector(), DTM_MASK, PARAM::exp_dirichlet, free_doublevector(), I_DIRICHLETMAPSERIES_COARSE, SQUARE_GRID::indices_pixel, join_strings(), RASTER_MAP::layer, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, PARAM::null_dirichlet, read_doublevector_from_raster(), S_TIMES::s_suffixes, S_TIMES::times, and RASTER_MAP::UV.
Referenced by time_loop().
S_TIMES* get_s_times (char * filename, short print)
Author
Emanuele Cordano
Date
29 May 2009
Parameters
filename (char *)
print (short)
Definition at line 127 of file b_sources.c.
References st::index, LONGVECTOR::nh, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, read_doublearray(), read_index(), read_stringarray(), S_TIMES::s_suffixes, t_error(), t_fclose(), t_fopen(), and S_TIMES::times.
Referenced by time_loop().
int get_sources (double t, DOUBLEVECTOR * sources)
Author
Emanuele Cordano
Date
May 2009
Parameters
t (double) time;
sources - (DOUBLEVECTOR *) sources
Definition at line 67 of file b_sources.c.
References A_FLAG, DOUBLESQUARE_GRID::big, DOUBLERASTER_MAP::coarse, copy_doublevector(), DTM_MASK, free_doublevector(), I_SOURCEMAPSERIES_COARSE, SQUARE_GRID::indices_pixel, join_strings(), RASTER_MAP::layer, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, read_doublevector_from_raster(), S_TIMES::s_suffixes, S_TIMES::times, and RASTER_MAP::UV.
Referenced by time_loop().