Boussinesq/b_v_advection.h File Reference
Functions
double F1_coefficient (long j, double velocity, double wet_vert_area)
double b_advection (long i)
double t_st_advection_operator_element (long i, DOUBLEVECTOR *eta, double cond_dirichlet)
double symmetric_surface_velocity (long j, double forcing)
double asymmetric_surface_velocity (long j, double eta_previous)
int update_velocity (DOUBLEVECTOR *eta)
int update_F1_wet_vert_area ()
Function Documentation
double asymmetric_surface_velocity (long j, double eta_previous)
Author
Emanuele Cordano
Date
October 2009
Parameters
j (long) line index
area_vert;
Definition at line 234 of file b_v_advection.c.
Referenced by b_advection(), and update_velocity().
double b_advection (long i)
Parameters
j - (long) index of the polygon
(global)velocity - (DOUBLEVECTOR *) eulerian velocity thourg the line
(global)wat_vert_area - (DOUBLEVECTOR *) - water vertical area over the j-th line multiplied by F1
Author
Emanuele Cordano
Date
October 2009
Definition at line 103 of file b_v_advection.c.
References asymmetric_surface_velocity(), GRID::boundary_indicator, DOUBLE_GRID::coarse, polygon_connection_attributes::connections, PARAM::dt, POLYGON::edge_indices, POLYGONVECTOR::element, polygon_connection_attribute_array::element, GRID::lines, GRID::links, LINEVECTOR::nh, POLYGONVECTOR::nh, DOUBLEVECTOR::nh, LINEVECTOR::nl, POLYGONVECTOR::nl, LONGVECTOR::nl, GRID::polygons, vertical_area_surf(), and water_surface_elevation_mean().
Referenced by time_loop().
double F1_coefficient (long j, double velocity, double wet_vert_area)
Parameters
j - (long) index of the line
velocity - (double) eulerian velocity thourg the line
wat_vert_area - (double) - water vertical area over the j-th line
Author
Emanuele Cordano
Date
October 2009
Definition at line 75 of file b_v_advection.c.
References DOUBLE_GRID::coarse, PARAM::dt, LINEVECTOR::element, LINE::length2d, GRID::lines, and PARAM::p_runoff.
Referenced by update_F1_wet_vert_area().
double symmetric_surface_velocity (long j, double forcing)
Author
Emanuele Cordano
Date
October 2009
Parameters
j - (long) index of the line \
eta - (DOUBLEVECTOR *) water surface elevation
Definition at line 216 of file b_v_advection.c.
References PARAM::dt, and PARAM::gravity.
Referenced by t_st_advection_operator_element(), and update_velocity().
double t_st_advection_operator_element (long i, DOUBLEVECTOR * eta, double cond_dirichlet)
Definition at line 161 of file b_v_advection.c.
References GRID::boundary_indicator, DOUBLE_GRID::coarse, polygon_connection_attributes::connections, polygon_connection_attributes::d_connections, PARAM::dt, POLYGON::edge_indices, POLYGONVECTOR::element, polygon_connection_attribute_array::element, GRID::lines, GRID::links, LINEVECTOR::nh, POLYGONVECTOR::nh, DOUBLEVECTOR::nh, LINEVECTOR::nl, POLYGONVECTOR::nl, LONGVECTOR::nl, GRID::polygons, symmetric_surface_velocity(), vertical_area_surf(), and water_surface_elevation_mean().
Referenced by t_st_operator_element(), and t_st_operator_element_no_dirichlet().
int update_F1_wet_vert_area ()
Author
Emanuele Cordano October 2009
Parameters
eta - (DOUBLEVECTOR *) water srface pressure
Definition at line 333 of file b_v_advection.c.
References GRID::boundary_indicator, DOUBLE_GRID::coarse, polygon_connection_attributes::connections, POLYGON::edge_indices, POLYGONVECTOR::element, polygon_connection_attribute_array::element, F1_coefficient(), GRID::lines, GRID::links, LINEVECTOR::nh, POLYGONVECTOR::nh, LONGVECTOR::nh, DOUBLEVECTOR::nh, LINEVECTOR::nl, POLYGONVECTOR::nl, DOUBLEVECTOR::nl, GRID::polygons, VELOCITY_INITIALIZATION_VALUE, vertical_area_surf(), and water_surface_elevation_mean().
Referenced by time_loop().
int update_velocity (DOUBLEVECTOR * eta)
Author
Emanuele Cordano
Date
October 2009
NOO
Parameters
(DOUBLEVECTOR *) - eta water surface
Definition at line 254 of file b_v_advection.c.
References asymmetric_surface_velocity(), GRID::boundary_indicator, DOUBLE_GRID::coarse, polygon_connection_attributes::connections, polygon_connection_attributes::d_connections, POLYGON::edge_indices, POLYGONVECTOR::element, polygon_connection_attribute_array::element, free_doublevector(), GRID::lines, GRID::links, new_doublevector(), LINEVECTOR::nh, POLYGONVECTOR::nh, LONGVECTOR::nh, DOUBLEVECTOR::nh, LINEVECTOR::nl, POLYGONVECTOR::nl, DOUBLEVECTOR::nl, GRID::polygons, symmetric_surface_velocity(), VELOCITY_INITIALIZATION_VALUE, and water_surface_elevation_mean().
Referenced by time_loop().