MATH2/boussinesq_matrix.h File Reference
Functions
DOUBLEBIN * get_t_Matrix_elements (t_Matrix_element operator, polygon_connection_attribute_array *pca, long boundary)
Function Documentation
DOUBLEBIN* get_t_Matrix_elements (t_Matrix_element operator, polygon_connection_attribute_array * pca, long boundary)
Date
January 2010
Author
Emanuele Cordano
Parameters
operator (t_Matrix_element) - The operator representing the sparse matrix
pca (*polygon_connection_attribute_array) - the polygon connetion ttributes pca
Returns
the sparse matrix as a DOUBLEBIN
Definition at line 19 of file boussinesq_matrix.c.
References polygon_connection_attributes::connections, polygon_connection_attribute_array::element, free_doublevector(), free_longvector(), db::index, new_doublebin(), new_doublevector(), new_longvector(), polygon_connection_attribute_array::nh, LONGVECTOR::nh, LONGVECTOR::nl, DOUBLEVECTOR::nl, and NULL_VALUE_bm.