MATH2/boussinesq_matrix.c File Reference
#include `turtle.h`
*
#include `t_utilities.h`
*
#include `doublevector_utilities.h`
*
#include `geometry.h`
*
#include `geometry_attribute.h`
*
#include `preconditioned_conjugate_gradient.h`
*
#include `boussinesq_matrix.h`
*
Macros
#define NULL_VALUE_bm -9999.0
Functions
DOUBLEBIN * get_t_Matrix_elements (t_Matrix_element operator, polygon_connection_attribute_array *pca, long boundary)
Macro Definition Documentation
#define NULL_VALUE_bm -9999.0
Definition at line 17 of file boussinesq_matrix.c.
Referenced by get_t_Matrix_elements().
Function Documentation
DOUBLEBIN* get_t_Matrix_elements (t_Matrix_element operator, polygon_connection_attribute_array * pca, long boundary)
Date
January 2010
Author
Emanuele Cordano
Parameters
operator (t_Matrix_element) - The operator representing the sparse matrix
pca (*polygon_connection_attribute_array) - the polygon connetion ttributes pca
Returns
the sparse matrix as a DOUBLEBIN
Definition at line 19 of file boussinesq_matrix.c.
References polygon_connection_attributes::connections, polygon_connection_attribute_array::element, free_doublevector(), free_longvector(), db::index, new_doublebin(), new_doublevector(), new_longvector(), polygon_connection_attribute_array::nh, LONGVECTOR::nh, LONGVECTOR::nl, DOUBLEVECTOR::nl, and NULL_VALUE_bm.