FLUIDTURTLES/error.c File Reference
#include `turtle.h`
*
Functions
void t_error (char *error_text)
Function Documentation
void t_error (char * error_text)
Definition at line 5 of file error.c.
Referenced by assignnovalue(), binarywrite_charvector_elements(), binarywrite_doublebin_elements(), binarywrite_doublematrix_elements(), binarywrite_doublevector_elements(), binarywrite_floatmatrix_elements(), binarywrite_floatvector_elements(), binarywrite_intbin_elements(), binarywrite_intmatrix_elements(), binarywrite_intvector_elements(), binarywrite_longbin_elements(), binarywrite_longmatrix_elements(), binarywrite_longvector_elements(), binarywrite_shortbin_elements(), binarywrite_shortmatrix_elements(), binarywrite_shortvector_elements(), buffer2list(), build_doubletensor(), build_frommatrix(), charmatrix(), clean_floatmatrix(), convlv(), copy_buffer_into_stringbin(), copy_doublematrix(), copy_doublevector(), copy_floatmatrix(), copy_floatvector(), copy_intmatrix(), copy_intvector(), copy_longmatrix(), copy_longvector(), copy_shortmatrix(), copy_shortvector(), cvector(), d3tensor(), decod(), delete_ijx(), delete_ix(), delete_longpair(), delete_longpoker(), delete_realpair(), delete_xyz(), deleteshuffle_longpair(), dmatrix(), double_n_moment(), doublematrix_element_multiplication(), doublematrix_n_moment(), doublevector_correlation(), doublevector_element_multiplication(), doublevector_n_moment(), dsprsax(), dsprstx(), dvector(), error_message(), esponentialsplit(), esponentialsplit2realvectors(), exponentialhystogram(), extract_doublematrix(), extract_fromtensor(), file_copy(), floatmatrix_element_multiplication(), floatmatrix_n_moment(), floatmatrix_restricted_n_moment(), floatvector_correlation(), floatvector_element_multiplication(), floatvector_n_moment(), fmultiplydoublematrix(), free_charvector(), free_doublebin(), free_doublematrix(), free_doubletensor(), free_doublevector(), free_floatmatrix(), free_floatvector(), free_intbin(), free_intmatrix(), free_intvector(), free_longbin(), free_longmatrix(), free_longvector(), free_shortbin(), free_shortmatrix(), free_shortvector(), free_stringbin(), get_doubleraster_map(), get_doublesquare_grid(), get_filename(), get_fine_indices(), get_parameter(), get_phrase(), get_s_times(), get_square_grid(), get_strings(), get_workingdirectory(), header_scan(), headercmp(), imatrix(), initialize_doublematrix(), initialize_doubletensor(), initialize_doublevector(), initialize_floatmatrix(), initialize_floatvector(), initialize_longmatrix(), initialize_longvector(), initialize_shortmatrix(), initialize_shortvector(), interpolate(), interpolate_doublematrix(), interpolate_floatmatrix(), ivector(), join_3strings_into(), join_strings_into(), justread_chararray(), justread_floatarray(), justread_floatmatrix(), justread_longarray(), linear_span_doubletensor(), lmatrix(), longmatrix_element_multiplication(), longmatrix_n_moment(), longvector_correlation(), longvector_element_multiplication(), longvector_n_moment(), lvector(), main(), matrix(), new_charvector(), new_connection_attributes(), new_doublebin(), new_doublematrix(), new_doubletensor(), new_doublevector(), new_floatmatrix(), new_floatvector(), new_ijx(), new_intbin(), new_intmatrix(), new_intvector(), new_ix(), new_line_from_points(), new_linevector(), new_longbin(), new_longmatrix(), new_longmatrix_vector(), new_longpair(), new_longpoker(), new_longvector(), new_output_filenames(), new_point(), new_polygon_from_a_linevector(), new_polygonvector(), new_raster_map(), new_realpair(), new_shortbin(), new_shortmatrix(), new_shortvector(), new_stringbin(), new_word(), new_xyz(), point2ijx(), point2ix(), point2longpair(), point2longpoker(), point2measure(), point2realpair(), print_charvector_elements(), print_doublebin_elements(), print_doublematrix_elements(), print_doubletensor_elements(), print_doublevector_elements(), print_floatmatrix_elements(), print_floatvector_elements(), print_intbin_elements(), print_intmatrix_elements(), print_intvector_elements(), print_longbin_elements(), print_longmatrix_elements(), print_longvector_elements(), print_shortbin_elements(), print_shortmatrix_elements(), print_shortvector_elements(), print_stringbin_elements(), prod_doublematvet(), prodscal(), query_for_label(), ran1(), read_b_parameters_ft(), read_buffer_from_stdio(), read_charvector(), read_charvector_elements(), read_comment(), read_doublearray(), read_doublebin(), read_doublebin_elements(), read_doublematrix(), read_doublematrix_elements(), read_doublesquare_grid(), read_doubletensor(), read_doubletensor_elements(), read_doublevector(), read_doublevector_elements(), read_esriascii(), read_filenames(), read_fine_indices(), read_floatarray(), read_floatmatrix(), read_floatmatrix_elements(), read_floatvector(), read_floatvector_elements(), read_grassascii(), read_grid(), read_index(), read_intbin(), read_intbin_elements(), read_intmatrix(), read_intmatrix_elements(), read_intvector(), read_intvector_elements(), read_keywords(), read_keywords_list(), read_longarray(), read_longbin(), read_longbin_elements(), read_longmatrix(), read_longmatrix_elements(), read_longvector(), read_longvector_elements(), read_map(), read_maptensor(), read_matrixheader(), read_parameters(), read_plane_strings(), read_plane_strings_restricted(), read_polygon(), read_shortarray(), read_shortbin(), read_shortbin_elements(), read_shortmatrix(), read_shortmatrix_elements(), read_shortvector(), read_shortvector_elements(), read_square_grid(), read_stringarray(), read_tensor(), read_tensorheader(), read_vectorheader(), readandstore_comment(), readline_array(), readline_textarray(), realbuffer2list(), realpair_into_doublematrix(), reorder_keywords_list(), search_array(), search_named_array(), shortmatrix_element_multiplication(), shortvector_element_multiplication(), simplefind(), simplehystogram(), smatrix(), split(), split2realvectors(), sprsin(), ssimplefindkeyword(), svector(), t_fopen(), tridiag(), vector(), vectorize_doublematrix(), vectorize_floatmatrix(), vectorize_longmatrix(), vectorize_shortmatrix(), write_chararray_elements(), write_charvector_elements(), write_comment(), write_doublearray_elements(), write_doublebin_elements(), write_doublematrix_elements(), write_doubletensor_elements(), write_doublevector_elements(), write_esriascii(), write_floatarray_elements(), write_floatmatrix_elements(), write_floatvector_elements(), write_frommatrix(), write_header_header(), write_intarray_elements(), write_intbin_elements(), write_intmatrix_elements(), write_intvector_elements(), write_longarray_elements(), write_longbin_elements(), write_longmatrix_elements(), write_longvector_elements(), write_read_filenames(), write_shortarray_elements(), write_shortbin_elements(), write_shortmatrix_elements(), write_shortvector_elements(), write_stringbin_elements(), write_stringsarray_elements(), write_suffix(), write_turtle(), and xyz_into_doublematrix().