BGEOMETRY/geometry2.c File Reference
#include `turtle.h`
*
#include `rw_maps.h`
*
#include `geometry.h`
*
#include `geometry_utilities.h`
*
#include `geometry_attribute.h`
*
#include `geometry_freememory.h`
*
#include `geometry_io.h`
*
#include `g_raster2plvector.h`
*
#include `sorting.h`
*
#include `linear_span.h`
*
#include `bigcells2.h`
*
#include `geometry2.h`
*
Functions
POINT * new_point_from_point (POINT *point)
LINE * new_line_from_line (LINE *line)
LINEVECTOR * new_linevector_from_linevector (LINEVECTOR *lines)
POLYGON * new_polygon_from_polygon (POLYGON *polygon)
POLYGONVECTOR * new_polygonvector_from_polygonvector (POLYGONVECTOR *polygons)
polygon_connection_attributes * new_connection_from_connection (polygon_connection_attributes *pc)
polygon_connection_attribute_array * new_connection_array_from_connection_array (polygon_connection_attribute_array *pca)
GRID * new_grid_from_grid (GRID *grid)
LONGBIN * new_longbin_from_doublematrix_array (LONGMATRIX_VECTOR *lmv)
LONGBIN * new_longbin_from_longbin (LONGBIN *lb)
DOUBLE_GRID * new_double_grid_from_doublesquare_grid (DOUBLESQUARE_GRID *dsq)
void free_DOUBLE_GRID (DOUBLE_GRID *dgrid)
LONGBIN * new_longbin_from_longbin_cleaning_novalues (LONGBIN *lb)
long bubble_sort_eleveation (long *cell_index, long nh, DOUBLEVECTOR *elevation)
int bubble_sort_elevation_in_longbin (LONGBIN *lb, DOUBLEVECTOR *elevation)
Function Documentation
int bubble_sort_elevation_in_longbin (LONGBIN * lb, DOUBLEVECTOR * elevation)
Author
Emanuele Cordano
Date
April 2010
Definition at line 520 of file geometry2.c.
References bubble_sort_eleveation(), LONGBIN::index, NL, and LONGVECTOR::nl.
Referenced by main().
long bubble_sort_eleveation (long * cell_index, long nh, DOUBLEVECTOR * elevation)
Author
Emanuele Cordano
Date
April 2001
Parameters
-(long *) cell_index : index of the cells
-(long) number of the cells in the rows
(DOUBLEVECTOR *) - map of elevation
sort the cell_indexes according with the increase of elevation.
swap cell_index[i] and cell_index[i+1]
swap cell_index[i] and cell_index[i+1]
Definition at line 451 of file geometry2.c.
References DOUBLEVECTOR::nh, and DOUBLEVECTOR::nl.
Referenced by bubble_sort_elevation_in_longbin().
void free_DOUBLE_GRID (DOUBLE_GRID * dgrid)
Parameters
\author Emanuele Cordano
Date
April 2010
Definition at line 350 of file geometry2.c.
References DOUBLE_GRID::coarse, DOUBLE_GRID::fine, free_grid(), free_longbin(), DOUBLE_GRID::small_line_content, and DOUBLE_GRID::small_polygon_content.
Referenced by main().
polygon_connection_attribute_array* new_connection_array_from_connection_array (polygon_connection_attribute_array * pca)
Parameters
(polygon_connection_attribute_array *) - polygon_connection_attribute_array
Author
Emanuele Cordano
Date
April 2010
Definition at line 163 of file geometry2.c.
References polygon_connection_attribute_array::element, new_connection_attributes(), new_connection_from_connection(), polygon_connection_attribute_array::nh, and polygon_connection_attribute_array::nl.
Referenced by new_grid_from_grid().
polygon_connection_attributes* new_connection_from_connection (polygon_connection_attributes * pc)
Definition at line 130 of file geometry2.c.
References polygon_connection_attributes::connections, polygon_connection_attributes::d_connections, new_doublevector(), new_longvector(), LONGVECTOR::nh, DOUBLEVECTOR::nh, LONGVECTOR::nl, and DOUBLEVECTOR::nl.
Referenced by new_connection_array_from_connection_array().
DOUBLE_GRID* new_double_grid_from_doublesquare_grid (DOUBLESQUARE_GRID * dsq)
Author
Emanuele Cordano
Date
April 2010
Definition at line 321 of file geometry2.c.
References DOUBLESQUARE_GRID::big, DOUBLE_GRID::coarse, dgrid, DOUBLE_GRID::fine, DOUBLESQUARE_GRID::fine, SQUARE_GRID::grid, new_grid_from_grid(), new_longbin_from_doublematrix_array(), new_longbin_from_longbin_cleaning_novalues(), DOUBLE_GRID::novalue, SQUARE_GRID::novalue, DOUBLESQUARE_GRID::small_content_line, DOUBLESQUARE_GRID::small_content_polygon, DOUBLE_GRID::small_line_content, and DOUBLE_GRID::small_polygon_content.
Referenced by main().
GRID* new_grid_from_grid (GRID * grid)
Author
Emanuele Cordano
Date
April 2010
Definition at line 187 of file geometry2.c.
References GRID::boundary_indicator, copy_string(), GRID::file_resume_connections, GRID::file_resume_lines, GRID::file_resume_polygons, GRID::lines, GRID::links, new_connection_array_from_connection_array(), new_linevector_from_linevector(), new_polygonvector_from_polygonvector(), and GRID::polygons.
Referenced by new_double_grid_from_doublesquare_grid().
LINE* new_line_from_line (LINE * line)
Parameters
(LINE *) line
Author
Emanuele Cordano
Date
April 2010
Definition at line 31 of file geometry2.c.
References LINE::begin, LINE::end, LINE::index, and new_line_from_points().
Referenced by new_linevector_from_linevector().
LINEVECTOR* new_linevector_from_linevector (LINEVECTOR * lines)
Parameters
(LINEVECTOR *) line
Author
Emanuele Cordano
Date
April 2010
Definition at line 55 of file geometry2.c.
References LINEVECTOR::element, new_line_from_line(), new_linevector(), LINEVECTOR::nh, and LINEVECTOR::nl.
Referenced by new_grid_from_grid().
LONGBIN * new_longbin_from_doublematrix_array (LONGMATRIX_VECTOR * lmv)
The following functions transforms a DOUBLESQUARE_GRID into a DOUBLEGRID
Parameters
(LONGMATRIX_VECTOR *) - lmv
(long) - novalue
Author
Emanuele Cordano
Definition at line 232 of file geometry2.c.
References LONGMATRIX_VECTOR::element, free_longvector(), LONGBIN::index, LONGMATRIX::ncl, new_longbin(), new_longvector(), LONGMATRIX_VECTOR::nh, LONGVECTOR::nh, LONGMATRIX_VECTOR::nl, NL, LONGVECTOR::nl, and LONGMATRIX::nrl.
Referenced by new_double_grid_from_doublesquare_grid().
LONGBIN* new_longbin_from_longbin (LONGBIN * lb)
Parameters
(LONGBIN *) - lb
Author
Emanuele Cordano
Date
April 2010
Definition at line 296 of file geometry2.c.
References LONGBIN::index, new_longbin(), NL, and LONGVECTOR::nl.
LONGBIN* new_longbin_from_longbin_cleaning_novalues (LONGBIN * lb)
Parameters
(LONGBIN *) - lb
Author
Emanuele Cordano
Date
April 2010
Definition at line 369 of file geometry2.c.
References free_longvector(), LONGBIN::index, new_longbin(), new_longvector(), LONGVECTOR::nh, NL, LONGVECTOR::nl, and stop_execution().
Referenced by new_double_grid_from_doublesquare_grid().
POINT* new_point_from_point (POINT * point)
Parameters
(POINT *) point
Author
Emanuele Cordano
Date
April 2010
Definition at line 15 of file geometry2.c.
References POINT::index, new_point(), POINT::x, POINT::y, and POINT::z.
Referenced by new_polygon_from_polygon().
POLYGON* new_polygon_from_polygon (POLYGON * polygon)
Parameters
(POLYGON *) polygon;
Author
Emanuele Cordano
Definition at line 78 of file geometry2.c.
References POLYGON::area2D, POLYGON::centroid, POLYGON::edge_indices, POLYGON::index, new_longvector(), new_point_from_point(), LONGVECTOR::nh, and LONGVECTOR::nl.
Referenced by new_polygonvector_from_polygonvector().
POLYGONVECTOR* new_polygonvector_from_polygonvector (POLYGONVECTOR * polygons)
Parameters
(POLYGONVECTOR *) - polygons
Author
Emanuele Cordano
Date
April 2010
Definition at line 107 of file geometry2.c.
References POLYGONVECTOR::element, new_polygon_from_polygon(), new_polygonvector(), POLYGONVECTOR::nh, and POLYGONVECTOR::nl.
Referenced by new_grid_from_grid().