BGEOMETRY/geometry_freememory.c File Reference
#include `turtle.h`
*
#include `geometry.h`
*
#include `t_datamanipulation.h`
*
#include `geometry_utilities.h`
*
#include `geometry_attribute.h`
*
#include `geometry_freememory.h`
*
Functions
void free_point (POINT *P)
void free_line (LINE *L)
void free_polygon (POLYGON *PO)
void free_linevector (LINEVECTOR *lv)
void free_polygonvector (POLYGONVECTOR *pv)
void free_point_attributes (attribute_point *point)
void free_line_attributes (attribute_line *line)
void free_polygon_attributes (attribute_polygon *polygon)
void free_polygon_connection_attributes (polygon_connection_attributes *pca)
void free_polygon_connection_attribute_array (polygon_connection_attribute_array *pcaa)
Function Documentation
void free_line (LINE * L)
Author
Emanuele Cordano
Date
November 2008
Definition at line 48 of file geometry_freememory.c.
References LINE::begin, LINE::end, and free_point().
Referenced by free_linevector().
void free_line_attributes (attribute_line * line)
Definition at line 123 of file geometry_freememory.c.
void free_linevector (LINEVECTOR * lv)
Author
Emanuele Cordano
Date
November 2008
Definition at line 77 of file geometry_freememory.c.
References LINEVECTOR::element, free_line(), and LINEVECTOR::nl.
Referenced by free_grid(), get_polygon(), and new_pixel_from_raster().
void free_point (POINT * P)
BGEOMETRY BUILDS THE MESH FROM A RASTER FOR THE BOUSSINESQ MODEL
 KeyPalette Version 0.9375 KMackenzie
file geometry_freememory.c
Copyright, 2009 Emanuele Cordano and Riccardo Rigon
This file is part of BGEOMETRY. BGEOMETRY is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
BGEOMETRY is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Emanuele Cordano
Date
November 2008
if (P) printf (`Warning: point %ld was not deallacated!!`,P->index);
Definition at line 34 of file geometry_freememory.c.
Referenced by free_line(), free_polygon(), get_line(), get_polygon(), new_horizontal_line_from_raster(), new_pixel_from_raster(), new_vertical_line_from_raster(), and read_linevector().
void free_point_attributes (attribute_point * point)
The following routines lines must be rewritten and rebuilt if attribute struct type are changed!!
Definition at line 116 of file geometry_freememory.c.
void free_polygon (POLYGON * PO)
Author
Emanuele Cordano
Date
November 2008
Definition at line 63 of file geometry_freememory.c.
References POLYGON::centroid, POLYGON::edge_indices, free_longvector(), and free_point().
Referenced by free_polygonvector().
void free_polygon_attributes (attribute_polygon * polygon)
Definition at line 130 of file geometry_freememory.c.
void free_polygon_connection_attribute_array (polygon_connection_attribute_array * pcaa)
Definition at line 144 of file geometry_freememory.c.
References polygon_connection_attribute_array::element, free_polygon_connection_attributes(), polygon_connection_attribute_array::nh, and polygon_connection_attribute_array::nl.
Referenced by free_grid().
void free_polygon_connection_attributes (polygon_connection_attributes * pca)
Definition at line 137 of file geometry_freememory.c.
References polygon_connection_attributes::connections, polygon_connection_attributes::d_connections, free_doublevector(), and free_longvector().
Referenced by free_polygon_connection_attribute_array().
void free_polygonvector (POLYGONVECTOR * pv)
Author
Emanuele Cordano
Date
November 2008
Definition at line 96 of file geometry_freememory.c.
References POLYGONVECTOR::element, free_polygon(), and POLYGONVECTOR::nl.
Referenced by free_grid().