KeyPalette/get_filenames.c File Reference
#include `turtle.h`
*
#include `t_io.h`
*
#include `key.palette.h`
*
#include `get_filenames.h`
*
Macros
#define INIT `.init`
#define INPTS `.inpts`
#define NOFILE_NAME join_strings(WORKING_DIRECTORY,`MISSING_FILE`)
Functions
STRINGBIN * get_filenames_from_keys (char *WORKING_DIRECTORY, char *program, short print)
Macro Definition Documentation
#define INIT `.init`
Definition at line 28 of file get_filenames.c.
Referenced by get_filenames_from_keys().
#define INPTS `.inpts`
Definition at line 29 of file get_filenames.c.
Referenced by get_filenames_from_keys().
#define NOFILE_NAME join_strings(WORKING_DIRECTORY,`MISSING_FILE`)
Definition at line 32 of file get_filenames.c.
Referenced by get_filenames_from_keys().
Function Documentation
STRINGBIN* get_filenames_from_keys (char * WORKING_DIRECTORY, char * program, short print)
Definition at line 34 of file get_filenames.c.
References KEYWORDS::comments, free_keywords(), free_stringbin(), INIT, INPTS, join_path_to_stringbin(), join_strings(), KEYWORDS::names, NOFILE_NAME, read_index(), read_keywords(), read_names(), t_fclose(), t_fopen(), write_keywords(), and write_read_filenames().
Referenced by main().