KeyPalette/get_filenames.h File Reference
Functions
STRINGBIN * get_filenames_from_keys (char *WORKING_DIRECTORY, char *program, short print)
Function Documentation
STRINGBIN* get_filenames_from_keys (char * WORKING_DIRECTORY, char * program, short print)
Definition at line 34 of file get_filenames.c.
References KEYWORDS::comments, free_keywords(), free_stringbin(), INIT, INPTS, join_path_to_stringbin(), join_strings(), KEYWORDS::names, NOFILE_NAME, read_index(), read_keywords(), read_names(), t_fclose(), t_fopen(), write_keywords(), and write_read_filenames().
Referenced by main().