ASCII/import_ascii.h File Reference
Functions
double * read_grassascii (double *header, double novalue, char *name, long max_figures)
double * read_esriascii (double *header, double novalue, char *name, long max_figures)
void error_message (short format, long n, long n1, long n2, long n3, char *name)
Function Documentation
void error_message (short format, long n, long n1, long n2, long n3, char * name)
Definition at line 551 of file import_ascii.c.
References ascii_esri, ascii_grass, join_strings(), and t_error().
Referenced by read_esriascii(), and read_grassascii().
double* read_esriascii (double * header, double novalue, char * name, long max_figures)
Definition at line 223 of file import_ascii.c.
References ascii_esri, error_message(), join_strings(), stop_execution(), and t_error().
Referenced by read_map().
double* read_grassascii (double * header, double novalue, char * name, long max_figures)
Definition at line 33 of file import_ascii.c.
References ascii_grass, error_message(), join_strings(), stop_execution(), and t_error().
Referenced by read_map().