KeyPalette/read_command_line.h File Reference
Macros
#define PRINT_FLAG `-print`
#define PRINT_ACTIVATED read_flag(argc,argv,PRINT_FLAG,0)
Functions
char * read_option_string (int argc, char *argv[], char *option_f, char *no_option_argument, short print)
double read_option_double (int argc, char *argv[], char *option_f, char *no_option_argument, double default_value, short print)
int read_flag (int argc, char *argv[], char *flag, short print)
Macro Definition Documentation
#define PRINT_ACTIVATED read_flag(argc,argv,PRINT_FLAG,0)
Definition at line 33 of file read_command_line.h.
#define PRINT_FLAG `-print`
flag which prints possible warning message
Definition at line 32 of file read_command_line.h.
Function Documentation
int read_flag (int argc, char * argv[], char * flag, short print)
Definition at line 117 of file read_command_line.c.
References NO_SUCCESS, and SUCCESS.
Referenced by main().
double read_option_double (int argc, char * argv[], char * option_f, char * no_option_argument, double default_value, short print)
Definition at line 83 of file read_command_line.c.
References read_option_string().
char* read_option_string (int argc, char * argv[], char * option_f, char * no_option_argument, short print)
Definition at line 38 of file read_command_line.c.
References NO_SUCCESS.
Referenced by main(), and read_option_double().