KeyPalette/read_command_line.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include `read_command_line.h`
*
Macros
#define SUCCESS 1
#define NO_SUCCESS 0
Functions
char * read_option_string (int argc, char *argv[], char *option_f, char *no_option_argument, short print)
double read_option_double (int argc, char *argv[], char *option_f, char *no_option_argument, double default_value, short print)
int read_flag (int argc, char *argv[], char *flag, short print)
Macro Definition Documentation
#define NO_SUCCESS 0
Definition at line 33 of file read_command_line.c.
Referenced by read_flag(), and read_option_string().
#define SUCCESS 1
Definition at line 32 of file read_command_line.c.
Referenced by read_flag().
Function Documentation
int read_flag (int argc, char * argv[], char * flag, short print)
Definition at line 117 of file read_command_line.c.
References NO_SUCCESS, and SUCCESS.
Referenced by main().
double read_option_double (int argc, char * argv[], char * option_f, char * no_option_argument, double default_value, short print)
Definition at line 83 of file read_command_line.c.
References read_option_string().
char* read_option_string (int argc, char * argv[], char * option_f, char * no_option_argument, short print)
Definition at line 38 of file read_command_line.c.
References NO_SUCCESS.
Referenced by main(), and read_option_double().