ASCII/rw_maps.c File Reference
#include `turtle.h`
*
#include `tensor3D.h`
*
#include `t_utilities.h`
*
#include `rw_maps.h`
*
#include `import_ascii.h`
*
#include `write_ascii.h`
*
#include `extensions.h`
*
Functions
SHORTMATRIX * copyshort_doublematrix (DOUBLEMATRIX *M)
LONGMATRIX * copylong_doublematrix (DOUBLEMATRIX *M)
DOUBLEMATRIX * copydouble_shortmatrix (SHORTMATRIX *S)
DOUBLEMATRIX * copydouble_longmatrix (LONGMATRIX *L)
DOUBLEMATRIX * copydoublematrix_const (double c0, DOUBLEMATRIX *Mref, double NOVALUE)
DOUBLEMATRIX * multiplydoublematrix (double f, DOUBLEMATRIX *Mref, double NOVALUE)
void build_doubletensor (DOUBLETENSOR *T, DOUBLEMATRIX *M, long l)
DOUBLEMATRIX * extract_doublematrix (DOUBLETENSOR *T, long l)
DOUBLEMATRIX * extract_fromtensor (DOUBLETENSOR *T, long l)
DOUBLETENSOR * build_frommatrix (DOUBLEMATRIX *M, long l, long lmax)
void write_frommatrix (long l, DOUBLEMATRIX *M, DOUBLETENSOR *T)
void fmultiplydoublematrix (DOUBLEMATRIX *destination, DOUBLEMATRIX *origin, double f, double novalue)
void assignnovalue (DOUBLEMATRIX *destination, DOUBLEMATRIX *origin, double novalue)
void write_suffix (char *suffix, long i, short start)
char * namefile_i (char *name, long i)
char * namefile_i_we (char *name, long i)
char * namefile_i_we2 (char *name, long i)
short existing_file (char *name)
short existing_file_text (char *name)
DOUBLEMATRIX * read_map (short a, char *filename, DOUBLEMATRIX *Mref, T_INIT *UVref)
DOUBLEMATRIX * read_mapseries (long i, char *filename, DOUBLEMATRIX *Mref, T_INIT *UVref)
DOUBLETENSOR * read_tensor (long nl, char *filename, DOUBLEMATRIX *Mref, T_INIT *UVref)
DOUBLETENSOR * read_maptensor (long i, long lmax, char *filename, DOUBLEMATRIX *Mref, T_INIT *UVref)
void write_map (char *filename, short type, short format, DOUBLEMATRIX *M, T_INIT *UV)
void write_mapseries (long i, char *filename, short type, short format, DOUBLEMATRIX *M, T_INIT *UV)
void write_tensorseries (short a, long l, long i, char *filename, short type, short format, DOUBLETENSOR *T, T_INIT *UV)
void write_tensorseries_bis (short a, long l, long i, char *filename, short type, short format, DOUBLETENSOR *T, T_INIT *UV)
void write_tensorseries2 (long i, char *filename, short type, short format, DOUBLETENSOR *T, T_INIT *UV)
Function Documentation
void assignnovalue (DOUBLEMATRIX * destination, DOUBLEMATRIX * origin, double novalue)
Definition at line 287 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, and t_error().
void build_doubletensor (DOUBLETENSOR * T, DOUBLEMATRIX * M, long l)
Definition at line 159 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLETENSOR::co, DOUBLEMATRIX::nch, DOUBLETENSOR::nch, DOUBLETENSOR::ndh, DOUBLEMATRIX::nrh, DOUBLETENSOR::nrh, and t_error().
DOUBLETENSOR* build_frommatrix (DOUBLEMATRIX * M, long l, long lmax)
Definition at line 223 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLETENSOR::co, initialize_doubletensor(), DOUBLEMATRIX::nch, new_doubletensor(), DOUBLEMATRIX::nrh, and t_error().
Referenced by read_maptensor(), and read_tensor().
DOUBLEMATRIX* copydouble_longmatrix (LONGMATRIX * L)
Definition at line 94 of file rw_maps.c.
References DOUBLEMATRIX::co, LONGMATRIX::co, LONGMATRIX::nch, new_doublematrix(), and LONGMATRIX::nrh.
DOUBLEMATRIX* copydouble_shortmatrix (SHORTMATRIX * S)
Definition at line 74 of file rw_maps.c.
References SHORTMATRIX::co, DOUBLEMATRIX::co, SHORTMATRIX::nch, new_doublematrix(), and SHORTMATRIX::nrh.
DOUBLEMATRIX* copydoublematrix_const (double c0, DOUBLEMATRIX * Mref, double NOVALUE)
Definition at line 113 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLEMATRIX::nch, new_doublematrix(), and DOUBLEMATRIX::nrh.
LONGMATRIX* copylong_doublematrix (DOUBLEMATRIX * M)
Definition at line 55 of file rw_maps.c.
References DOUBLEMATRIX::co, LONGMATRIX::co, DOUBLEMATRIX::nch, new_longmatrix(), and DOUBLEMATRIX::nrh.
SHORTMATRIX* copyshort_doublematrix (DOUBLEMATRIX * M)
Definition at line 36 of file rw_maps.c.
References SHORTMATRIX::co, DOUBLEMATRIX::co, DOUBLEMATRIX::nch, new_shortmatrix(), and DOUBLEMATRIX::nrh.
short existing_file (char * name)
Definition at line 390 of file rw_maps.c.
References ascii_esri, ascii_ft, ascii_grass, and join_strings().
Referenced by read_map().
short existing_file_text (char * name)
Definition at line 418 of file rw_maps.c.
References join_strings(), and textfile.
DOUBLEMATRIX* extract_doublematrix (DOUBLETENSOR * T, long l)
Definition at line 178 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLETENSOR::co, DOUBLEMATRIX::nch, DOUBLETENSOR::nch, DOUBLETENSOR::ndh, new_doublematrix(), DOUBLEMATRIX::nrh, DOUBLETENSOR::nrh, and t_error().
DOUBLEMATRIX* extract_fromtensor (DOUBLETENSOR * T, long l)
Definition at line 202 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLETENSOR::co, DOUBLETENSOR::nch, DOUBLETENSOR::ndh, new_doublematrix(), DOUBLETENSOR::nrh, and t_error().
void fmultiplydoublematrix (DOUBLEMATRIX * destination, DOUBLEMATRIX * origin, double f, double novalue)
Definition at line 267 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, and t_error().
DOUBLEMATRIX* multiplydoublematrix (double f, DOUBLEMATRIX * Mref, double NOVALUE)
Definition at line 136 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLEMATRIX::nch, new_doublematrix(), and DOUBLEMATRIX::nrh.
char* namefile_i (char * name, long i)
Definition at line 347 of file rw_maps.c.
References join_strings(), textfile, and write_suffix().
char* namefile_i_we (char * name, long i)
Definition at line 361 of file rw_maps.c.
References join_strings(), and write_suffix().
char* namefile_i_we2 (char * name, long i)
Definition at line 374 of file rw_maps.c.
References join_strings(), and write_suffix().
DOUBLEMATRIX* read_map (short a, char * filename, DOUBLEMATRIX * Mref, T_INIT * UVref)
Definition at line 435 of file rw_maps.c.
References ascii_esri, ascii_ft, ascii_grass, DOUBLEVECTOR::co, DOUBLEMATRIX::co, existing_file(), free_doublevector(), join_strings(), DOUBLEMATRIX::nch, new_doublematrix(), new_doublevector(), DOUBLEMATRIX::nrh, PRINT, read_doublearray(), read_doublematrix(), read_esriascii(), read_grassascii(), read_index(), stop_execution(), t_error(), t_fclose(), t_fopen(), T_INIT::U, and T_INIT::V.
Referenced by add_map_to_raster(), read_doublevector_from_raster(), read_mapseries(), and read_maptensor().
DOUBLEMATRIX* read_mapseries (long i, char * filename, DOUBLEMATRIX * Mref, T_INIT * UVref)
Definition at line 625 of file rw_maps.c.
References join_strings(), read_map(), and write_suffix().
Referenced by read_tensor().
DOUBLETENSOR* read_maptensor (long i, long lmax, char * filename, DOUBLEMATRIX * Mref, T_INIT * UVref)
Definition at line 667 of file rw_maps.c.
References build_frommatrix(), join_strings(), read_map(), t_error(), write_frommatrix(), and write_suffix().
DOUBLETENSOR* read_tensor (long nl, char * filename, DOUBLEMATRIX * Mref, T_INIT * UVref)
Definition at line 642 of file rw_maps.c.
References build_frommatrix(), free_doublematrix(), read_mapseries(), t_error(), and write_frommatrix().
void write_frommatrix (long l, DOUBLEMATRIX * M, DOUBLETENSOR * T)
Definition at line 247 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLETENSOR::co, DOUBLEMATRIX::nch, DOUBLETENSOR::nch, DOUBLETENSOR::ndh, DOUBLEMATRIX::nrh, DOUBLETENSOR::nrh, and t_error().
Referenced by read_maptensor(), and read_tensor().
void write_map (char * filename, short type, short format, DOUBLEMATRIX * M, T_INIT * UV)
Definition at line 697 of file rw_maps.c.
References write_esriascii(), write_fluidturtle(), and write_grassascii().
Referenced by write_mapseries(), write_raster_from_doublevector(), write_raster_from_doublevector_v2(), write_tensorseries(), and write_tensorseries_bis().
void write_mapseries (long i, char * filename, short type, short format, DOUBLEMATRIX * M, T_INIT * UV)
Definition at line 719 of file rw_maps.c.
References join_strings(), write_map(), and write_suffix().
void write_suffix (char * suffix, long i, short start)
Definition at line 304 of file rw_maps.c.
References t_error().
Referenced by namefile_i(), namefile_i_we(), namefile_i_we2(), read_mapseries(), read_maptensor(), time_loop(), write_mapseries(), write_tensorseries(), and write_tensorseries_bis().
void write_tensorseries (short a, long l, long i, char * filename, short type, short format, DOUBLETENSOR * T, T_INIT * UV)
Definition at line 731 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLETENSOR::co, free_doublematrix(), join_strings(), DOUBLETENSOR::nch, new_doublematrix(), DOUBLETENSOR::nrh, write_map(), and write_suffix().
void write_tensorseries2 (long i, char * filename, short type, short format, DOUBLETENSOR * T, T_INIT * UV)
Definition at line 804 of file rw_maps.c.
References DOUBLETENSOR::ndh, and write_tensorseries_bis().
void write_tensorseries_bis (short a, long l, long i, char * filename, short type, short format, DOUBLETENSOR * T, T_INIT * UV)
Definition at line 766 of file rw_maps.c.
References DOUBLEMATRIX::co, DOUBLETENSOR::co, free_doublematrix(), join_strings(), DOUBLETENSOR::nch, new_doublematrix(), DOUBLETENSOR::nrh, write_map(), and write_suffix().
Referenced by write_tensorseries2().