FLUIDTURTLES/statistics.c File Reference
#include `turtle.h`
*
#include `t_statistics.h`
*
Macros
#define MAXCOUNTER 3
Functions
float longvector_n_moment (LONGVECTOR *v, float mean, float NN, long novalue)
float floatvector_n_moment (FLOATVECTOR *v, float mean, float NN, float novalue)
double doublevector_n_moment (DOUBLEVECTOR *v, float mean, float NN, double novalue)
float floatmatrix_n_moment (FLOATMATRIX *m, float mean, float NN, float novalue)
double doublematrix_n_moment (DOUBLEMATRIX *m, double mean, double NN, double novalue)
float longmatrix_n_moment (LONGMATRIX *m, double mean, double NN, long novalue)
float floatmatrix_restricted_n_moment (FLOATMATRIX *m, FLOATMATRIX *s, float mean, float NN, float novalue, float novalue2)
float longvector_correlation (LONGVECTOR *v, LONGVECTOR *u, float m1, float m2, long r, long novalue)
float floatvector_correlation (FLOATVECTOR *v, FLOATVECTOR *u, float m1, float m2, long r, float novalue)
double doublevector_correlation (DOUBLEVECTOR *v, DOUBLEVECTOR *u, double m1, double m2, long r, double novalue)
double double_n_moment (double *m, long nh, double mean, double NN, double novalue)
Macro Definition Documentation
#define MAXCOUNTER 3
Definition at line 3 of file statistics.c.
Function Documentation
double double_n_moment (double * m, long nh, double mean, double NN, double novalue)
Definition at line 526 of file statistics.c.
References t_error().
double doublematrix_n_moment (DOUBLEMATRIX * m, double mean, double NN, double novalue)
Definition at line 236 of file statistics.c.
References DOUBLEMATRIX::co, DOUBLEMATRIX::isdynamic, DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, and t_error().
double doublevector_correlation (DOUBLEVECTOR * , DOUBLEVECTOR * , double , double , long , double)
Name: doublevector_correlation, floatvector_correlation, longvector_correlation
Synopsis: double doublevector_correlation(DOUBLEVECTOR *,DOUBLEVECTOR *,double ,double ,long ,double); float floatvector_correlation(FLOATVECTOR *,FLOATVECTOR *u,float ,float ,long ,float); float longvector_correlation(LONGVECTOR *,LONGVECTOR *,float,float ,long ,long);
Description: It calculates the biased corretion between two vectors of the specified type.
Inputs: 1) the first vector; 2) the second vector; 3) the first vector mean; 4) the second vector mean; 5) the lag at which the correlation is calculated; 6) the value that identify `NO DATA`
Return: biased correlation (the division factor is the length of the vector minus the number of missing data)
FILE: LIBRARIES/BASICMATHSTAT/statistics.c, LIBRARIES/BASICMATHSTAT/t_statistics.h
Examples: hystogram.c
Authors & Date: Paolo D'Odorico, Riccardo Rigon, February 1998.
References: Probability, Statistics, and Reliability for Civil and Environmental Engineers
Definition at line 490 of file statistics.c.
References DOUBLEVECTOR::co, DOUBLEVECTOR::isdynamic, DOUBLEVECTOR::nh, and t_error().
double doublevector_n_moment (DOUBLEVECTOR * v, float mean, float NN, double novalue)
Definition at line 117 of file statistics.c.
References DOUBLEVECTOR::co, DOUBLEVECTOR::isdynamic, DOUBLEVECTOR::nh, and t_error().
float floatmatrix_n_moment (FLOATMATRIX * m, float mean, float NN, float novalue)
Definition at line 174 of file statistics.c.
References FLOATMATRIX::co, FLOATMATRIX::isdynamic, FLOATMATRIX::nch, FLOATMATRIX::nrh, and t_error().
float floatmatrix_restricted_n_moment (FLOATMATRIX * , FLOATMATRIX * , float , float , float , float)
Name:floatmatrix_restricted _n_moment
Synopsis: float floatmatrix_n_moment(FLOATMATRIX *first,FLOATMATRIX *second, float ,float , float,float);
Description: It calculates the biased n moment of a vector or a matrix of the specified type as floatmatrix_n_moment but it uses the subset of points that are not novalue2 in a second nmatrix
Inputs: 1) the first matrix; 2) The second matrix; 3) the first matrix mean; 4) the second matrix mean; 5) the value that identify `NO DATA` or `MISSING DATA` in the first matrix (a sequence of mesasured data usually contains points where the data were not detected or monitored); 6) the vector that identify `NO DATA` in the second matrix
Return: biased n moment (the division factor is the length of the vector minus the number of missing data)
Authors & date: Paolo D'Odorico, Riccardo Rigon, February 1998.
FILE: LIBRARIES/BASICMATHSTAT/statistics.c, LIBRARIES/BASICMATHSTAT/t_statistics.h
Examples: LIBRARIES/APPLICATIONS/GEOMORPHOLOGY/RIVER_NETWORKS/sum_downstream.c
Definition at line 357 of file statistics.c.
References FLOATMATRIX::co, FLOATMATRIX::isdynamic, FLOATMATRIX::nch, FLOATMATRIX::nrh, and t_error().
float floatvector_correlation (FLOATVECTOR * v, FLOATVECTOR * u, float m1, float m2, long r, float novalue)
Definition at line 456 of file statistics.c.
References FLOATVECTOR::co, FLOATVECTOR::isdynamic, FLOATVECTOR::nh, and t_error().
float floatvector_n_moment (FLOATVECTOR * v, float mean, float NN, float novalue)
Definition at line 61 of file statistics.c.
References FLOATVECTOR::co, FLOATVECTOR::isdynamic, FLOATVECTOR::nh, and t_error().
float longmatrix_n_moment (LONGMATRIX * , double , double , long)
Name: _n_moment
Synopsis: float longmatrix_n_moment(LONGMATRIX *, double ,double , long); double doublematrix_n_moment(DOUBLEMATRIX *, double ,double , double); float floatmatrix_n_moment(FLOATMATRIX *, float ,float , float); double doublevector_n_moment(DOUBLEVECTOR *, float ,float , double); float floatvector_n_moment(FLOATVECTOR *, float ,float , float); float longvector_n_moment(LONGVECTOR *, float ,float , long);
Description: It calculates the biased n moment of a vector or a matrix of the specified type
Inputs: 1) the first vector; 2) the second vector; 3) the first vector mean; 4) the second vector mean; 5) the value that identify `NO DATA` or `MISSING DATA` (a sequence of mesasured data usually contains points where the data were not detected or monitored)
Return: biased n moment (the division factor is the length of the vector minus the number of missing data)
Examples: LIBRARIES/APPLICATIONS/DATA_MANIPULATION/hystogram.c
See Also: doublevector_correlation
Authors & date: Paolo D'Odorico, Riccardo Rigon, February 1998.
FILE: LIBRARIES/BASICMATHSTAT/statistics.c, LIBRARIES/BASICMATHSTAT/t_statistics.h
Definition at line 298 of file statistics.c.
References LONGMATRIX::co, LONGMATRIX::isdynamic, LONGMATRIX::nch, LONGMATRIX::nrh, and t_error().
float longvector_correlation (LONGVECTOR * v, LONGVECTOR * u, float m1, float m2, long r, long novalue)
Definition at line 421 of file statistics.c.
References LONGVECTOR::co, LONGVECTOR::isdynamic, LONGVECTOR::nh, and t_error().
float longvector_n_moment (LONGVECTOR * v, float mean, float NN, long novalue)
Definition at line 6 of file statistics.c.
References LONGVECTOR::co, LONGVECTOR::isdynamic, LONGVECTOR::nh, and t_error().