FLUIDTURTLES/string.c File Reference
#include `turtle.h`
*
Functions
STRINGBIN * read_plane_strings_restricted (FILE *inputfile, long length, long maxbuffersize)
Function Documentation
STRINGBIN * read_plane_strings_restricted (FILE * inputfile, long length, long maxbuffersize)
Definition at line 5 of file string.c.
References BUFFERINCREMENT, LONGVECTOR::co, copy_buffer_into_stringbin(), free_longvector(), new_longvector(), new_stringbin(), LONGVECTOR::nh, skip_whitespaces(), and t_error().