FLUIDTURTLES/t_alloc.h File Reference
Functions
float * vector (long nl, long nh)
int * ivector (long nl, long nh)
long * lvector (long nl, long nh)
short * svector (long nl, long nh)
double * dvector (long nl, long nh)
char * cvector (long nl, long nh)
float ** matrix (long nrl, long nrh, long ncl, long nch)
int ** imatrix (long nrl, long nrh, long ncl, long nch)
short ** smatrix (long nrl, long nrh, long ncl, long nch)
long ** lmatrix (long nrl, long nrh, long ncl, long nch)
double ** dmatrix (long nrl, long nrh, long ncl, long nch)
char ** charmatrix (long nrl, long nrh, long ncl, long nch)
SHORTVECTOR * new_shortvector (long)
INTVECTOR * new_intvector (long)
FLOATVECTOR * new_floatvector (long)
LONGVECTOR * new_longvector (long)
DOUBLEVECTOR * new_doublevector (long)
CHARVECTOR * new_charvector (long)
SHORTMATRIX * new_shortmatrix (long, long)
INTMATRIX * new_intmatrix (long, long)
FLOATMATRIX * new_floatmatrix (long, long)
LONGMATRIX * new_longmatrix (long, long)
DOUBLEMATRIX * new_doublematrix (long, long)
INTBIN * new_intbin (LONGVECTOR *)
STRINGBIN * new_stringbin (LONGVECTOR *)
SHORTBIN * new_shortbin (LONGVECTOR *)
LONGBIN * new_longbin (LONGVECTOR *)
DOUBLEBIN * new_doublebin (LONGVECTOR *)
void free_shortvector (SHORTVECTOR *)
void free_intvector (INTVECTOR *)
void free_longvector (LONGVECTOR *)
void free_floatvector (FLOATVECTOR *)
void free_doublevector (DOUBLEVECTOR *)
void free_charvector (CHARVECTOR *)
void free_shortmatrix (SHORTMATRIX *)
void free_intmatrix (INTMATRIX *)
void free_longmatrix (LONGMATRIX *)
void free_floatmatrix (FLOATMATRIX *)
void free_doublematrix (DOUBLEMATRIX *)
void free_intbin (INTBIN *)
void free_stringbin (STRINGBIN *)
void free_shortbin (SHORTBIN *)
void free_longbin (LONGBIN *)
void free_doublebin (DOUBLEBIN *)
void free_svector (short *v, long nl)
void free_ivector (int *v, long nl)
void free_vector (float *v, long nl)
void free_lvector (long *v, long nl)
void free_dvector (double *v, long nl)
void free_cvector (char *v, long nl)
void free_smatrix (short **m, long nrl, long ncl)
void free_imatrix (int **m, long nrl, long ncl)
void free_matrix (float **m, long nrl, long ncl)
void free_lmatrix (long **m, long nrl, long ncl)
void free_dmatrix (double **m, long nrl, long ncl)
void free_charmatrix (char **m, long nrl, long ncl)
void free_header (HEADER)
double *** d3tensor (long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
DOUBLETENSOR * new_doubletensor (long nrh, long nch, long ndh)
void free_d3tensor (double ***t, long nrl, long ncl, long ndl)
void free_doubletensor (DOUBLETENSOR *m)
Function Documentation
char** charmatrix (long nrl, long nrh, long ncl, long nch)
Definition at line 741 of file alloc.c.
References NR_END, and t_error().
char* cvector (long nl, long nh)
Definition at line 237 of file alloc.c.
References NR_END, and t_error().
Referenced by new_charvector().
double*** d3tensor (long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
Definition at line 9 of file tensors3D.c.
References NR_END, and t_error().
Referenced by new_doubletensor().
double** dmatrix (long nrl, long nrh, long ncl, long nch)
Definition at line 654 of file alloc.c.
References NR_END, and t_error().
Referenced by new_doublematrix().
double* dvector (long nl, long nh)
Definition at line 189 of file alloc.c.
References NR_END, and t_error().
Referenced by new_doublevector().
void free_charmatrix (char ** m, long nrl, long ncl)
Definition at line 2613 of file alloc.c.
References FREE_ARG, and NR_END.
void free_charvector (CHARVECTOR *)
Definition at line 3027 of file alloc.c.
References CHARVECTOR::co, free_cvector(), CHARVECTOR::isdynamic, CHARVECTOR::nh, NL, CHARVECTOR::nl, and t_error().
void free_cvector (char * v, long nl)
Definition at line 2425 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_charvector().
void free_d3tensor (double *** t, long nrl, long ncl, long ndl)
Definition at line 83 of file tensors3D.c.
References FREE_ARG, and NR_END.
Referenced by free_doubletensor().
void free_dmatrix (double ** m, long nrl, long ncl)
Definition at line 2578 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_doublematrix().
void free_doublebin (DOUBLEBIN *)
Definition at line 3739 of file alloc.c.
References db::co, FREE_ARG, free_longvector(), db::index, db::isdynamic, LONGVECTOR::nl, NR_END, and t_error().
void free_doublematrix (DOUBLEMATRIX *)
Definition at line 3414 of file alloc.c.
References DOUBLEMATRIX::co, free_dmatrix(), DOUBLEMATRIX::isdynamic, DOUBLEMATRIX::nch, DOUBLEMATRIX::ncl, NL, DOUBLEMATRIX::nrh, DOUBLEMATRIX::nrl, and t_error().
Referenced by add_map_to_raster(), doubletensor_dem(), free_raster_map(), get_doublematrix_from_mapseries(), ordi_kriging2(), read_doublevector_from_raster(), read_linevector(), read_tensor(), write_raster_from_doublevector(), write_raster_from_doublevector_v2(), write_tensorseries(), and write_tensorseries_bis().
void free_doubletensor (DOUBLETENSOR * m)
Definition at line 97 of file tensors3D.c.
References DOUBLETENSOR::co, free_d3tensor(), DOUBLETENSOR::isdynamic, DOUBLETENSOR::nch, DOUBLETENSOR::ncl, DOUBLETENSOR::ndh, DOUBLETENSOR::ndl, NL, DOUBLETENSOR::nrh, DOUBLETENSOR::nrl, and t_error().
void free_doublevector (DOUBLEVECTOR *)
Definition at line 2952 of file alloc.c.
References DOUBLEVECTOR::co, free_dvector(), DOUBLEVECTOR::isdynamic, DOUBLEVECTOR::nh, NL, DOUBLEVECTOR::nl, and t_error().
Referenced by free_polygon_connection_attributes(), free_raster_map(), free_s_times(), get_diagonal(), get_dirichletsnode(), get_doublematrix_from_mapseries(), get_doublevector_for_lines(), get_sources(), get_t_Matrix_elements(), jacobi_preconditioned_conjugate_gradient_search(), ludcmp(), main(), Newton_convergence(), ordi_kriging2(), read_b_parameters_ft(), read_connections(), read_doublearray_from_string(), read_map(), read_polygon(), time_loop(), tridiag(), update_velocity(), write_cell(), write_line_map(), and write_lines().
void free_dvector (double * v, long nl)
Definition at line 2398 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_doublevector().
void free_floatmatrix (FLOATMATRIX *)
Definition at line 3261 of file alloc.c.
References FLOATMATRIX::co, free_matrix(), FLOATMATRIX::isdynamic, FLOATMATRIX::nch, FLOATMATRIX::ncl, NL, FLOATMATRIX::nrh, FLOATMATRIX::nrl, and t_error().
void free_floatvector (FLOATVECTOR *)
Definition at line 2799 of file alloc.c.
References FLOATVECTOR::co, free_vector(), FLOATVECTOR::isdynamic, FLOATVECTOR::nh, NL, FLOATVECTOR::nl, and t_error().
Referenced by convlv().
void free_header (HEADER)
Name: free_header
Version: 1.0
Synopsis: void free_header(HEADER)
General information: This section includes the deallocation routines for blocks and header. Types HEADER are allocated by read_header.
Authors & Date: Riccardo Rigon 1996-1997
FILE: LIBRARIES/BASICS/t_alloc.h, LIBRARIES/BASICS/alloc.c
Inputs: the name of the structure to be deallocated
Return: void
Examples: 1.example.c, 2.example.c
Keywords: Dynamic memory allocation, Pointers.
Definition at line 3954 of file alloc.c.
References HEADER::name.
Referenced by justread_floatmatrix(), read_charvector(), read_doublearray(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_longbin(), read_longmatrix(), read_longvector(), read_shortbin(), read_shortmatrix(), read_shortvector(), and read_stringarray().
void free_imatrix (int ** m, long nrl, long ncl)
Definition at line 2488 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_intmatrix().
void free_intbin (INTBIN *)
Definition at line 3492 of file alloc.c.
References INTBIN::co, FREE_ARG, free_longvector(), INTBIN::index, INTBIN::isdynamic, LONGVECTOR::nl, NR_END, and t_error().
void free_intmatrix (INTMATRIX *)
Definition at line 3180 of file alloc.c.
References INTMATRIX::co, free_imatrix(), INTMATRIX::isdynamic, INTMATRIX::nch, INTMATRIX::ncl, NL, INTMATRIX::nrh, INTMATRIX::nrl, and t_error().
void free_intvector (INTVECTOR *)
Definition at line 2724 of file alloc.c.
References INTVECTOR::co, free_ivector(), INTVECTOR::isdynamic, INTVECTOR::nh, NL, INTVECTOR::nl, and t_error().
void free_ivector (int * v, long nl)
Definition at line 2314 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_intvector().
void free_lmatrix (long ** m, long nrl, long ncl)
Definition at line 2548 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_longmatrix().
void free_longbin (LONGBIN *)
Definition at line 3653 of file alloc.c.
References LONGBIN::co, FREE_ARG, free_longvector(), LONGBIN::index, LONGBIN::isdynamic, LONGVECTOR::nl, NR_END, and t_error().
Referenced by free_DOUBLE_GRID(), free_doublesquare_grid(), and m_indices_from_mask().
void free_longmatrix (LONGMATRIX *)
Definition at line 3339 of file alloc.c.
References LONGMATRIX::co, free_lmatrix(), LONGMATRIX::isdynamic, LONGMATRIX::nch, LONGMATRIX::ncl, NL, LONGMATRIX::nrh, LONGMATRIX::nrl, and t_error().
Referenced by free_longmatrix_vector(), free_square_grid(), and m_indices_from_mask().
void free_longvector (LONGVECTOR *)
Definition at line 2874 of file alloc.c.
References LONGVECTOR::co, free_lvector(), LONGVECTOR::isdynamic, LONGVECTOR::nh, NL, LONGVECTOR::nl, and t_error().
Referenced by addresses(), free_doublebin(), free_intbin(), free_longbin(), free_polygon(), free_polygon_connection_attributes(), free_shortbin(), free_stringbin(), get_fine_line_indices(), get_line(), get_polygon(), get_t_Matrix_elements(), join_path_to_stringbin(), m_indices_with_novalues(), new_longbin_from_doublematrix_array(), new_longbin_from_longbin_cleaning_novalues(), new_pixel_from_raster(), new_polygon_from_a_linevector(), read_doublebin(), read_intbin(), read_keywords(), read_line_indices(), read_longarray_from_string(), read_longbin(), read_names(), read_plane_strings(), read_plane_strings_restricted(), read_shortbin(), and reorder_keywords_list().
void free_lvector (long * v, long nl)
Definition at line 2371 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_longvector().
void free_matrix (float ** m, long nrl, long ncl)
Definition at line 2518 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_floatmatrix().
void free_shortbin (SHORTBIN *)
Definition at line 3571 of file alloc.c.
References SHORTBIN::co, FREE_ARG, free_longvector(), SHORTBIN::index, SHORTBIN::isdynamic, LONGVECTOR::nl, NR_END, and t_error().
void free_shortmatrix (SHORTMATRIX *)
Definition at line 3102 of file alloc.c.
References SHORTMATRIX::co, free_smatrix(), SHORTMATRIX::isdynamic, SHORTMATRIX::nch, SHORTMATRIX::ncl, NL, SHORTMATRIX::nrh, SHORTMATRIX::nrl, and t_error().
void free_shortvector (SHORTVECTOR *)
Name: free_
Description: This section includes the deallocation routines for the vector, matrixes and bins
Version: 1.0
Synopsis: void free_shortvector(SHORTVECTOR *); void free_intvector(INTVECTOR *); void free_longvector(LONGVECTOR *); void free_floatvector(FLOATVECTOR *); void free_doublevector(DOUBLEVECTOR *); void free_charvector(CHARVECTOR *);
void free_shortmatrix(SHORTMATRIX *); void free_intmatrix(INTMATRIX *); void free_longmatrix(LONGMATRIX *); void free_floatmatrix(FLOATMATRIX *); void free_doublematrix(DOUBLEMATRIX *);
void free_intbin(INTBIN *); void free_stringbin(STRINGBIN *); void free_shortbin(SHORTBIN *); void free_longbin(LONGBIN *); void free_doublebin(DOUBLEBIN *);
Authors & date: Paolo D'Odorico, Riccardo Rigon 1996-1997
FILE: LIBRARIES/BASICS/t_alloc.h, LIBRARIES/BASICS/alloc.c
Inputs: the name of the structure to be deallocated
Return: void
Related Routines: free, malloc
Keywords: Dynamic memory allocation, Pointers.
Examples: 1.example.c, 2.example.c
Definition at line 2649 of file alloc.c.
References SHORTVECTOR::co, free_svector(), SHORTVECTOR::isdynamic, SHORTVECTOR::nh, NL, SHORTVECTOR::nl, and t_error().
Referenced by ordi_kriging2().
void free_smatrix (short ** m, long nrl, long ncl)
Definition at line 2458 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_shortmatrix().
void free_stringbin (STRINGBIN *)
Definition at line 3829 of file alloc.c.
References st::co, FREE_ARG, free_longvector(), st::index, st::isdynamic, LONGVECTOR::nl, NR_END, and t_error().
Referenced by free_keywords(), free_s_times(), get_filenames_from_keys(), main(), and read_keywords().
void free_svector (short * v, long nl)
Definition at line 2287 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_shortvector().
void free_vector (float * v, long nl)
Definition at line 2344 of file alloc.c.
References FREE_ARG, and NR_END.
Referenced by free_floatvector().
int** imatrix (long nrl, long nrh, long ncl, long nch)
Definition at line 381 of file alloc.c.
References NR_END, and t_error().
Referenced by new_intmatrix().
int* ivector (long nl, long nh)
Definition at line 63 of file alloc.c.
References NR_END, and t_error().
Referenced by new_intvector().
long** lmatrix (long nrl, long nrh, long ncl, long nch)
Definition at line 567 of file alloc.c.
References NR_END, and t_error().
Referenced by new_longmatrix().
long* lvector (long nl, long nh)
Definition at line 105 of file alloc.c.
References NR_END, and t_error().
Referenced by new_longvector().
float** matrix (long nrl, long nrh, long ncl, long nch)
Definition at line 294 of file alloc.c.
References NR_END, and t_error().
Referenced by doubletensor_dem(), and new_floatmatrix().
CHARVECTOR* new_charvector (long)
Definition at line 1131 of file alloc.c.
References CHARVECTOR::co, cvector(), isDynamic, CHARVECTOR::isdynamic, CHARVECTOR::nh, NL, CHARVECTOR::nl, and t_error().
Referenced by read_charvector().
DOUBLEBIN* new_doublebin (LONGVECTOR *)
Definition at line 1932 of file alloc.c.
References co, LONGVECTOR::co, db::co, db::index, isDynamic, db::isdynamic, new_longvector(), db::next, LONGVECTOR::nh, LONGVECTOR::nl, NR_END, and t_error().
Referenced by get_t_Matrix_elements(), and read_doublebin().
DOUBLEMATRIX* new_doublematrix (long , long)
Definition at line 1425 of file alloc.c.
References DOUBLEMATRIX::co, dmatrix(), isDynamic, DOUBLEMATRIX::isdynamic, DOUBLEMATRIX::nch, DOUBLEMATRIX::ncl, NL, DOUBLEMATRIX::nrh, DOUBLEMATRIX::nrl, and t_error().
Referenced by add_map_to_raster(), aggregate(), cleandata_matrix(), copydouble_longmatrix(), copydouble_shortmatrix(), copydoublematrix_const(), doublemap_from_longmap(), doubletensor_dem(), exponentialhystogram(), extract_doublematrix(), extract_fromtensor(), get_doublemap_spav(), get_doublematrix_from_doublevector(), get_doublematrix_from_mapseries(), interpolating_function(), multiplydoublematrix(), ordi_kriging2(), quickinterpolate(), read_doublematrix(), read_map(), ricampiona(), shrink_doublematrix(), simplehystogram(), transpose_doublematrix(), vett_mat(), write_tensorseries(), and write_tensorseries_bis().
DOUBLETENSOR* new_doubletensor (long nrh, long nch, long ndh)
Definition at line 53 of file tensors3D.c.
References DOUBLETENSOR::co, d3tensor(), isDynamic, DOUBLETENSOR::isdynamic, DOUBLETENSOR::nch, DOUBLETENSOR::ncl, DOUBLETENSOR::ndh, DOUBLETENSOR::ndl, NL, DOUBLETENSOR::nrh, DOUBLETENSOR::nrl, and t_error().
Referenced by build_frommatrix(), linear_span_doubletensor(), and read_doubletensor().
DOUBLEVECTOR* new_doublevector (long)
Definition at line 1074 of file alloc.c.
References DOUBLEVECTOR::co, dvector(), isDynamic, DOUBLEVECTOR::isdynamic, DOUBLEVECTOR::nh, NL, DOUBLEVECTOR::nl, and t_error().
Referenced by extract_a_column_from_doublematrix(), extract_a_row_from_doublematrix(), extract_a_vertical_column_from_doubletensor(), get_connection(), get_connection_squares(), get_diagonal(), get_doublevector_for_lines(), get_doublevector_from_doublematrix(), get_t_Matrix_elements(), interpolete_volume2lines(), jacobi_preconditioned_conjugate_gradient_search(), ludcmp(), main(), new_connection_from_connection(), Newton_convergence(), ordi_kriging2(), prod_doublematvet(), read_connections(), read_doublearray(), read_doublearray_from_string(), read_doublevector(), read_map(), scalxvet(), time_loop(), tridiag(), update_velocity(), write_cell(), write_line_map(), and write_lines().
FLOATMATRIX* new_floatmatrix (long , long)
Definition at line 1308 of file alloc.c.
References FLOATMATRIX::co, isDynamic, FLOATMATRIX::isdynamic, matrix(), FLOATMATRIX::nch, FLOATMATRIX::ncl, NL, FLOATMATRIX::nrh, FLOATMATRIX::nrl, and t_error().
Referenced by read_floatmatrix().
FLOATVECTOR* new_floatvector (long)
Definition at line 957 of file alloc.c.
References FLOATVECTOR::co, isDynamic, FLOATVECTOR::isdynamic, FLOATVECTOR::nh, NL, FLOATVECTOR::nl, t_error(), and vector().
Referenced by aggregate(), convlv(), read_floatarray(), read_floatvector(), and ricampiona().
INTBIN* new_intbin (LONGVECTOR *)
Definition at line 1479 of file alloc.c.
References co, LONGVECTOR::co, INTBIN::co, INTBIN::index, isDynamic, INTBIN::isdynamic, new_longvector(), LONGVECTOR::nh, LONGVECTOR::nl, NR_END, and t_error().
Referenced by read_intbin().
INTMATRIX* new_intmatrix (long , long)
Definition at line 1248 of file alloc.c.
References INTMATRIX::co, imatrix(), isDynamic, INTMATRIX::isdynamic, INTMATRIX::nch, INTMATRIX::ncl, NL, INTMATRIX::nrh, INTMATRIX::nrl, and t_error().
Referenced by read_intmatrix().
INTVECTOR* new_intvector (long)
Definition at line 903 of file alloc.c.
References INTVECTOR::co, isDynamic, INTVECTOR::isdynamic, ivector(), INTVECTOR::nh, NL, INTVECTOR::nl, and t_error().
Referenced by read_intvector().
LONGBIN* new_longbin (LONGVECTOR *)
Definition at line 1782 of file alloc.c.
References co, LONGVECTOR::co, LONGBIN::co, LONGBIN::index, isDynamic, LONGBIN::isdynamic, new_longvector(), LONGVECTOR::nh, LONGVECTOR::nl, NR_END, and t_error().
Referenced by addresses(), get_fine_line_indices(), new_longbin_from_doublematrix_array(), new_longbin_from_longbin(), new_longbin_from_longbin_cleaning_novalues(), read_line_indices(), and read_longbin().
LONGMATRIX* new_longmatrix (long , long)
Definition at line 1368 of file alloc.c.
References LONGMATRIX::co, isDynamic, LONGMATRIX::isdynamic, lmatrix(), LONGMATRIX::nch, LONGMATRIX::ncl, NL, LONGMATRIX::nrh, LONGMATRIX::nrl, and t_error().
Referenced by copylong_doublematrix(), get_fine_indices(), m_indices_from_mask(), m_indices_with_novalues(), and read_longmatrix().
LONGVECTOR* new_longvector (long)
Definition at line 1014 of file alloc.c.
References LONGVECTOR::co, isDynamic, LONGVECTOR::isdynamic, lvector(), LONGVECTOR::nh, NL, LONGVECTOR::nl, and t_error().
Referenced by addresses(), addresses_bubble_sort(), esponentialsplit(), esponentialsplit2realvectors(), get_connection(), get_connection_squares(), get_fine_line_indices(), get_t_Matrix_elements(), join_path_to_stringbin(), m_indices_with_novalues(), new_connection_from_connection(), new_doublebin(), new_intbin(), new_longbin(), new_longbin_from_doublematrix_array(), new_longbin_from_longbin_cleaning_novalues(), new_pixel_from_raster(), new_polygon_from_a_linevector(), new_polygon_from_polygon(), new_shortbin(), new_stringbin(), read_connections(), read_keywords(), read_line_indices(), read_longarray(), read_longarray_from_string(), read_longvector(), read_names(), read_plane_strings(), read_plane_strings_restricted(), read_polygon(), read_stringarray(), reorder_keywords_list(), split(), and split2realvectors().
SHORTBIN* new_shortbin (LONGVECTOR *)
Definition at line 1632 of file alloc.c.
References co, LONGVECTOR::co, SHORTBIN::co, SHORTBIN::index, isDynamic, SHORTBIN::isdynamic, new_longvector(), LONGVECTOR::nh, LONGVECTOR::nl, NR_END, and t_error().
Referenced by read_shortbin().
SHORTMATRIX* new_shortmatrix (long , long)
Definition at line 1188 of file alloc.c.
References SHORTMATRIX::co, isDynamic, SHORTMATRIX::isdynamic, SHORTMATRIX::nch, SHORTMATRIX::ncl, NL, SHORTMATRIX::nrh, SHORTMATRIX::nrl, smatrix(), and t_error().
Referenced by copyshort_doublematrix(), and read_shortmatrix().
SHORTVECTOR* new_shortvector (long)
Name: new_
Synopsis:
SHORTVECTOR *new_shortvector(long);
INTVECTOR *new_intvector(long);
FLOATVECTOR *new_floatvector(long);
LONGVECTOR *new_longvector(long);
DOUBLEVECTOR *new_doublevector(long);
CHARVECTOR *new_charvector(long);
SHORTMATRIX *new_shortmatrix(long,long);
INTMATRIX *new_intmatrix(long,long);
FLOATMATRIX *new_floatmatrix(long,long);
LONGMATRIX *new_longmatrix(long,long);
DOUBLEMATRIX *new_doublematrix(long,long);
INTBIN *new_intbin(LONGVECTOR *);
STRINGBIN *new_stringbin(LONGVECTOR *);
SHORTBIN *new_shortbin(LONGVECTOR *);
LONGBIN *new_longbin(LONGVECTOR *);
DOUBLEBIN *new_doublebin(LONGVECTOR *);
Version: 1.0
Description: Allocate vectors, matrixes and bind. Strings length is not known apriori. Thus, the allocation program is one with the reading routine one finds in t_io.h.
Authors & Date: Paolo D'Odorico, Riccardo Rigon, 1996-1997
FILE: LIBRARIES/BASICS/t_alloc.h, LIBRARIES/BASICS/alloc.c
Inputs: the number of elements in the vector, the number of rows and columns matrixes, a LONGVECTOR for bins.
Return: a pointer to the allocated structure
See Also: vector, free
Keywords: Dynamic memory allocation, pointers.
Examples: 1.example.c, 2.example.c
Definition at line 846 of file alloc.c.
References SHORTVECTOR::co, isDynamic, SHORTVECTOR::isdynamic, SHORTVECTOR::nh, NL, SHORTVECTOR::nl, svector(), and t_error().
Referenced by esponentialsplit2realvectors(), ordi_kriging2(), read_shortarray(), and read_shortvector().
STRINGBIN* new_stringbin (LONGVECTOR *)
Definition at line 2094 of file alloc.c.
References co, LONGVECTOR::co, st::co, st::index, isDynamic, st::isdynamic, new_longvector(), st::next, LONGVECTOR::nh, LONGVECTOR::nl, NR_END, and t_error().
Referenced by join_path_to_stringbin(), read_keywords(), read_names(), read_plane_strings(), read_plane_strings_restricted(), read_stringarray(), and reorder_keywords_list().
short** smatrix (long nrl, long nrh, long ncl, long nch)
Definition at line 480 of file alloc.c.
References NR_END, and t_error().
Referenced by new_shortmatrix().
short* svector (long nl, long nh)
Definition at line 147 of file alloc.c.
References NR_END, and t_error().
Referenced by new_shortvector().
float* vector (long nl, long nh)
Definition at line 18 of file alloc.c.
References NR_END, and t_error().
Referenced by new_floatvector(), and new_longmatrix_vector().