FLUIDTURTLES/t_io.c File Reference
#include `turtle.h`
*
#include `t_utilities.h`
*
#include `tensor3D.h`
*
Functions
FILE * t_fopen (const char *name, const char *mode)
FILE * t_fclose (FILE *stream)
long read_shortvector_elements (FILE *input, SHORTVECTOR *v, char *mode)
long write_shortvector_elements (FILE *output, SHORTVECTOR *v, long maxcols)
long binarywrite_shortvector_elements (FILE *output, SHORTVECTOR *v)
void print_shortvector_elements (SHORTVECTOR *v, long maxcols)
long read_intvector_elements (FILE *input, INTVECTOR *v, char *mode)
long write_intvector_elements (FILE *output, INTVECTOR *v, long maxcols)
long binarywrite_intvector_elements (FILE *output, INTVECTOR *v)
void print_intvector_elements (INTVECTOR *v, long maxcols)
long read_longvector_elements (FILE *input, LONGVECTOR *v, char *mode)
long write_longvector_elements (FILE *output, LONGVECTOR *v, long maxcols)
long binarywrite_longvector_elements (FILE *output, LONGVECTOR *v)
void print_longvector_elements (LONGVECTOR *v, long maxcols)
long read_floatvector_elements (FILE *input, FLOATVECTOR *v, char *mode)
long write_floatvector_elements (FILE *output, FLOATVECTOR *v, long maxcols)
long binarywrite_floatvector_elements (FILE *output, FLOATVECTOR *v)
void print_floatvector_elements (FLOATVECTOR *v, long maxcols)
long read_doublevector_elements (FILE *input, DOUBLEVECTOR *v, char *mode)
long write_doublevector_elements (FILE *output, DOUBLEVECTOR *v, long maxcols)
long binarywrite_doublevector_elements (FILE *output, DOUBLEVECTOR *v)
void print_doublevector_elements (DOUBLEVECTOR *v, long maxcols)
long read_charvector_elements (FILE *input, CHARVECTOR *v, char *mode)
long write_charvector_elements (FILE *output, CHARVECTOR *v, long maxcols)
long binarywrite_charvector_elements (FILE *output, CHARVECTOR *v)
void print_charvector_elements (CHARVECTOR *v, long maxcols)
long read_shortmatrix_elements (FILE *input, SHORTMATRIX *m, char *mode)
long write_shortmatrix_elements (FILE *output, SHORTMATRIX *m, long maxcols)
long binarywrite_shortmatrix_elements (FILE *output, SHORTMATRIX *m)
void print_shortmatrix_elements (SHORTMATRIX *m, long maxcols)
long read_intmatrix_elements (FILE *input, INTMATRIX *m, char *mode)
long write_intmatrix_elements (FILE *output, INTMATRIX *m, long maxcols)
long binarywrite_intmatrix_elements (FILE *output, INTMATRIX *m)
void print_intmatrix_elements (INTMATRIX *m, long maxcols)
long read_longmatrix_elements (FILE *input, LONGMATRIX *m, char *mode)
long write_longmatrix_elements (FILE *output, LONGMATRIX *m, long maxcols)
long binarywrite_longmatrix_elements (FILE *output, LONGMATRIX *m)
void print_longmatrix_elements (LONGMATRIX *m, long maxcols)
long read_floatmatrix_elements (FILE *input, FLOATMATRIX *m, char *mode)
long write_floatmatrix_elements (FILE *output, FLOATMATRIX *m, long maxcols)
long binarywrite_floatmatrix_elements (FILE *output, FLOATMATRIX *m)
void print_floatmatrix_elements (FLOATMATRIX *m, long maxcols)
long read_doublematrix_elements (FILE *input, DOUBLEMATRIX *m, char *mode)
long write_doublematrix_elements (FILE *output, DOUBLEMATRIX *m, long maxcols)
long binarywrite_doublematrix_elements (FILE *output, DOUBLEMATRIX *m)
void print_doublematrix_elements (DOUBLEMATRIX *m, long maxcols)
long read_intbin_elements (FILE *input, INTBIN *l, char *mode)
long write_intbin_elements (FILE *output, INTBIN *l, long maxcols)
long binarywrite_intbin_elements (FILE *output, INTBIN *l)
void print_intbin_elements (INTBIN *l, long maxcols)
long read_shortbin_elements (FILE *input, SHORTBIN *l, char *mode)
long write_shortbin_elements (FILE *output, SHORTBIN *l, long maxcols)
long binarywrite_shortbin_elements (FILE *output, SHORTBIN *l)
void print_shortbin_elements (SHORTBIN *l, long maxcols)
long read_longbin_elements (FILE *input, LONGBIN *l, char *mode)
long write_longbin_elements (FILE *output, LONGBIN *l, long maxcols)
long binarywrite_longbin_elements (FILE *output, LONGBIN *l)
void print_longbin_elements (LONGBIN *l, long maxcols)
long read_doublebin_elements (FILE *input, DOUBLEBIN *l, char *mode)
long write_doublebin_elements (FILE *output, DOUBLEBIN *l, long maxcols)
long binarywrite_doublebin_elements (FILE *output, DOUBLEBIN *l)
void print_doublebin_elements (DOUBLEBIN *l, long maxcols)
STRINGBIN * read_plane_strings (FILE *inputfile, long length, long maxbuffersize)
long write_stringbin_elements (FILE *output, STRINGBIN *l, long maxcols)
void print_stringbin_elements (STRINGBIN *l, long maxcols)
int copy_buffer_into_stringbin (char *buffer, STRINGBIN *l)
long longvectorcmp (LONGVECTOR *A, LONGVECTOR *B)
void skip_whitespaces (FILE *inputfile)
void goto_EOF (FILE *inputfile)
int iscomment (char *buffer, FILE *inputfile)
char * get_workingdirectory (void)
char * join_strings (char *first, char *second)
char * get_filename (char *working_directory, char *program)
double get_parameter (char *working_directory, char *program)
char * get_strings (char *working_directory, char *program)
STRINGBIN * read_filenames (char *working_directory, char *program, char *extension, char *position)
DOUBLEVECTOR * read_parameters (char *working_directory, char *program, char *extension, char *position)
char * query_for_label (FILE *inputfile)
char * get_phrase (FILE *inputfile, const char separator)
int query_for_token (FILE *inputfile, const char *token)
int read_comment (FILE *inputfile, int opt, long maxbuffersize, short print)
char * readandstore_comment (FILE *inputfile, int opt, long maxbuffersize)
char * read_buffer_from_stdio (long maxbuffersize)
long read_index (FILE *inputfile, short print)
int header_scan (FILE *inputfile, HEADER *h)
long headercmp (HEADER *a, HEADER *b)
LONGVECTOR * read_longarray (FILE *inputfile, short print)
FLOATVECTOR * read_floatarray (FILE *inputfile, short print)
DOUBLEVECTOR * read_doublearray (FILE *inputfile, short print)
SHORTVECTOR * read_shortarray (FILE *inputfile, short print)
STRINGBIN * read_stringarray (FILE *inputfile, short print)
void justread_longarray (FILE *inputfile, LONGVECTOR *vec, short print)
void justread_floatarray (FILE *inputfile, FLOATVECTOR *vec, short print)
void justread_floatmatrix (FILE *inputfile, FLOATMATRIX *C, char *mode, short print)
void justread_chararray (FILE *inputfile, CHARVECTOR *vec, short print)
void read_vectorheader (FILE *inputfile, HEADER *h)
void read_matrixheader (FILE *inputfile, HEADER *h)
CHARVECTOR * read_charvector (FILE *inputfile, char *mode, short print)
SHORTVECTOR * read_shortvector (FILE *inputfile, char *mode, short print)
INTVECTOR * read_intvector (FILE *inputfile, char *mode, short print)
LONGVECTOR * read_longvector (FILE *inputfile, char *mode, short print)
FLOATVECTOR * read_floatvector (FILE *inputfile, char *mode, short print)
DOUBLEVECTOR * read_doublevector (FILE *inputfile, char *mode, short print)
SHORTMATRIX * read_shortmatrix (FILE *inputfile, char *mode, short print)
INTMATRIX * read_intmatrix (FILE *inputfile, char *mode, short print)
LONGMATRIX * read_longmatrix (FILE *inputfile, char *mode, short print)
FLOATMATRIX * read_floatmatrix (FILE *inputfile, char *mode, short print)
DOUBLEMATRIX * read_doublematrix (FILE *inputfile, char *mode, short print)
INTBIN * read_intbin (FILE *inputfile, char *mode, short print)
SHORTBIN * read_shortbin (FILE *inputfile, char *mode, short print)
LONGBIN * read_longbin (FILE *inputfile, char *mode, short print)
DOUBLEBIN * read_doublebin (FILE *inputfile, char *mode, short print)
void write_shortarray_elements (FILE *outputfile, SHORTVECTOR *V, long columns)
void write_intarray_elements (FILE *outputfile, INTVECTOR *V, long columns)
void write_longarray_elements (FILE *outputfile, LONGVECTOR *V, long columns)
void write_floatarray_elements (FILE *outputfile, FLOATVECTOR *V, long columns)
void write_doublearray_elements (FILE *outputfile, DOUBLEVECTOR *V, long columns)
void write_chararray_elements (FILE *outputfile, CHARVECTOR *V, long columns)
void write_stringsarray_elements (FILE *outputfile, STRINGBIN *V)
void print_header (HEADER *H)
void write_header_header (FILE *outputfile, HEADER *H)
void write_turtle (FILE *outputfile, char *creator, char *inputs)
void write_comment (FILE *outputfile, const char *comment, long columns)
long read_doubletensor_elements (FILE *input, DOUBLETENSOR *m, char *mode)
long write_doubletensor_elements (FILE *output, DOUBLETENSOR *m, long maxcols)
void print_doubletensor_elements (DOUBLETENSOR *m, long maxcols)
DOUBLETENSOR * read_doubletensor (FILE *inputfile, char *mode, short print)
void read_tensorheader (FILE *inputfile, HEADER *h)
Variables
char * WORKING_DIRECTORY ='\0'
FILE * EXTERNAL_FILE
LONGVECTOR * EXTERNAL_P
char EXTERNAL_FILE_NAME [256]
char OLD_NAME [256]
long int EXTERNAL_FILE_POSITION =SEEK_SET
HEADER EXTERNAL_HEADER
short OPENYES =0
long IO_FILES_COUNTER =0
long IO_STRINGS_COUNTER =0
long WORKING_POSITION =0
long IO_PARMS_COUNTER =0
t_keywords T_KEYWORDS
Function Documentation
long binarywrite_charvector_elements (FILE * output, CHARVECTOR * v)
 Write a vector of char to a file in binary mode
Definition at line 937 of file t_io.c.
References CHARVECTOR::co, CHARVECTOR::isdynamic, CHARVECTOR::nh, CHARVECTOR::nl, and t_error().
long binarywrite_doublebin_elements (FILE * output, DOUBLEBIN * l)
 Write a list of double to a file Here is still missing a check that output was open as `wb`
Definition at line 2523 of file t_io.c.
References LONGVECTOR::co, db::co, db::index, db::isdynamic, and t_error().
long binarywrite_doublematrix_elements (FILE * output, DOUBLEMATRIX * m)
 Write a matrix of double to a file
Definition at line 1803 of file t_io.c.
References DOUBLEMATRIX::co, DOUBLEMATRIX::isdynamic, DOUBLEMATRIX::nch, DOUBLEMATRIX::ncl, DOUBLEMATRIX::nrh, DOUBLEMATRIX::nrl, and t_error().
long binarywrite_doublevector_elements (FILE * output, DOUBLEVECTOR * v)
 Write a vector of double to a file in binary mode
Definition at line 786 of file t_io.c.
References DOUBLEVECTOR::co, DOUBLEVECTOR::isdynamic, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, and t_error().
long binarywrite_floatmatrix_elements (FILE * output, FLOATMATRIX * m)
 Write a matrix of float to a file
Definition at line 1632 of file t_io.c.
References FLOATMATRIX::co, FLOATMATRIX::isdynamic, FLOATMATRIX::nch, FLOATMATRIX::ncl, FLOATMATRIX::nrh, FLOATMATRIX::nrl, and t_error().
long binarywrite_floatvector_elements (FILE * output, FLOATVECTOR * v)
 Write a vector of float to a file in binary mode
Definition at line 635 of file t_io.c.
References FLOATVECTOR::co, FLOATVECTOR::isdynamic, FLOATVECTOR::nh, FLOATVECTOR::nl, and t_error().
long binarywrite_intbin_elements (FILE * output, INTBIN * l)
 Write a list of int to a file Here is still missing a check that output was open as `wb`
Definition at line 1980 of file t_io.c.
References LONGVECTOR::co, INTBIN::co, INTBIN::index, INTBIN::isdynamic, and t_error().
long binarywrite_intmatrix_elements (FILE * output, INTMATRIX * m)
 Write a matrix of int to a file
Definition at line 1281 of file t_io.c.
References INTMATRIX::co, INTMATRIX::isdynamic, INTMATRIX::nch, INTMATRIX::ncl, INTMATRIX::nrh, INTMATRIX::nrl, and t_error().
long binarywrite_intvector_elements (FILE * output, INTVECTOR * v)
 Write a vector of int to a file in binary mode
Definition at line 334 of file t_io.c.
References INTVECTOR::co, INTVECTOR::isdynamic, INTVECTOR::nh, INTVECTOR::nl, and t_error().
long binarywrite_longbin_elements (FILE * output, LONGBIN * l)
 Write a list of long to a file Here is still missing a check that output was open as `wb`
Definition at line 2342 of file t_io.c.
References LONGVECTOR::co, LONGBIN::co, LONGBIN::index, LONGBIN::isdynamic, and t_error().
long binarywrite_longmatrix_elements (FILE * output, LONGMATRIX * m)
 Write a matrix of long to a file
Definition at line 1455 of file t_io.c.
References LONGMATRIX::co, LONGMATRIX::isdynamic, LONGMATRIX::nch, LONGMATRIX::ncl, LONGMATRIX::nrh, LONGMATRIX::nrl, and t_error().
long binarywrite_longvector_elements (FILE * output, LONGVECTOR * v)
 Write a vector of long to a file in binary mode
Definition at line 485 of file t_io.c.
References LONGVECTOR::co, LONGVECTOR::isdynamic, LONGVECTOR::nh, LONGVECTOR::nl, and t_error().
long binarywrite_shortbin_elements (FILE * output, SHORTBIN * l)
 Write a list of short to a file Here is still missing a check that output was open as `wb`
Definition at line 2161 of file t_io.c.
References LONGVECTOR::co, SHORTBIN::co, SHORTBIN::index, SHORTBIN::isdynamic, and t_error().
long binarywrite_shortmatrix_elements (FILE * output, SHORTMATRIX * m)
 Write a matrix of shorts to a file
Definition at line 1110 of file t_io.c.
References SHORTMATRIX::co, SHORTMATRIX::isdynamic, SHORTMATRIX::nch, SHORTMATRIX::ncl, SHORTMATRIX::nrh, SHORTMATRIX::nrl, and t_error().
long binarywrite_shortvector_elements (FILE * output, SHORTVECTOR * v)
 Write a vector of short int to a file in binary mode
Definition at line 181 of file t_io.c.
References SHORTVECTOR::co, SHORTVECTOR::isdynamic, SHORTVECTOR::nh, SHORTVECTOR::nl, and t_error().
int copy_buffer_into_stringbin (char * buffer, STRINGBIN * l)
Definition at line 2830 of file t_io.c.
References co, st::co, st::index, st::isdynamic, OK, and t_error().
Referenced by read_plane_strings(), and read_plane_strings_restricted().
char* get_filename (char * working_directory, char * program)
Definition at line 3058 of file t_io.c.
References st::co, IO_FILES_COUNTER, join_strings(), NOPRINT, read_stringarray(), simplefind(), t_error(), t_fclose(), and WORKING_POSITION.
double get_parameter (char * working_directory, char * program)
Definition at line 3126 of file t_io.c.
References DOUBLEVECTOR::co, IO_PARMS_COUNTER, join_strings(), NOPRINT, read_doublearray(), simplefind(), t_error(), t_fclose(), and WORKING_POSITION.
char* get_phrase (FILE * inputfile, const char separator)
 isspace(label[i-1]) &&
Definition at line 3400 of file t_io.c.
References join_strings(), LABELINCREMENT, MAXLABELSIZE, skip_whitespaces(), t_error(), and WORKING_DIRECTORY.
Referenced by justread_floatmatrix(), read_charvector(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatmatrix(), read_floatvector(), read_intmatrix(), read_intvector(), read_longmatrix(), read_longvector(), read_shortmatrix(), and read_shortvector().
char* get_strings (char * working_directory, char * program)
Definition at line 3170 of file t_io.c.
References st::co, IO_FILES_COUNTER, join_strings(), NOPRINT, read_stringarray(), simplefind(), t_error(), t_fclose(), and WORKING_POSITION.
char* get_workingdirectory (void)
Definition at line 2992 of file t_io.c.
References t_error().
void goto_EOF (FILE * inputfile)
Definition at line 2927 of file t_io.c.
Referenced by read_charvector(), and read_intbin().
int header_scan (FILE * inputfile, HEADER * h)
Definition at line 4504 of file t_io.c.
References HEADER::category, t_keywords::category, HEADER::gender, t_keywords::gender, iscomment(), MAX_KEYWORD_LENGTH, MAXBUFFERSIZE, HEADER::name, NOPRINT, HEADER::number, OK, query_for_label(), read_comment(), skip_whitespaces(), t_error(), T_KEYWORDS, HEADER::type, and t_keywords::type.
Referenced by justread_chararray(), justread_floatarray(), justread_longarray(), read_doublearray(), read_floatarray(), read_longarray(), read_matrixheader(), read_shortarray(), read_stringarray(), read_tensorheader(), read_vectorheader(), search_array(), and search_named_array().
long headercmp (HEADER * a, HEADER * b)
Definition at line 4943 of file t_io.c.
References HEADER::category, HEADER::dimensions, HEADER::gender, HEADER::name, t_error(), and HEADER::type.
Referenced by justread_floatmatrix(), read_charvector(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatmatrix(), read_floatvector(), read_intmatrix(), read_intvector(), read_longmatrix(), read_longvector(), read_shortmatrix(), and read_shortvector().
int iscomment (char * buffer, FILE * inputfile)
Definition at line 2959 of file t_io.c.
References skip_whitespaces().
Referenced by header_scan(), read_comment(), read_index(), and readandstore_comment().
char* join_strings (char * first, char * second)
Definition at line 3039 of file t_io.c.
Referenced by doublematrix_control(), doublematrix_dem(), doublematrix_dem3(), doubletensor_dem(), doublevector_dem(), error_message(), existing_file(), existing_file_text(), floatmatrix_dem(), floatvector_dem(), get_dirichletsnode(), get_doublesquare_grid(), get_filename(), get_filenames_from_keys(), get_parameter(), get_phrase(), get_sources(), get_strings(), intmatrix_dem(), join_path_to_stringbin(), longmatrix_dem(), namefile_i(), namefile_i_we(), namefile_i_we2(), Newton_convergence(), read_doublesquare_grid(), read_esriascii(), read_filenames(), read_grassascii(), read_grid(), read_map(), read_mapseries(), read_maptensor(), read_names(), read_parameters(), shortmatrix_dem(), shortmatrix_dem3(), write_esriascii(), write_fluidturtle(), write_grassascii(), write_line_map(), write_map_results(), write_mapseries(), write_tensorseries(), and write_tensorseries_bis().
void justread_chararray (FILE * inputfile, CHARVECTOR * vec, short print)
Definition at line 6712 of file t_io.c.
References HEADER::category, CHARVECTOR::co, header_scan(), CHARVECTOR::isdynamic, CHARVECTOR::nh, print_header(), skip_whitespaces(), t_error(), and HEADER::type.
void justread_floatarray (FILE * inputfile, FLOATVECTOR * vec, short print)
Definition at line 6600 of file t_io.c.
References HEADER::category, FLOATVECTOR::co, header_scan(), FLOATVECTOR::isdynamic, FLOATVECTOR::nh, print_header(), skip_whitespaces(), t_error(), and HEADER::type.
void justread_floatmatrix (FILE * inputfile, FLOATMATRIX * C, char * mode, short print)
Definition at line 6642 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_floatmatrix_elements(), read_index(), read_matrixheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
void justread_longarray (FILE * inputfile, LONGVECTOR * vec, short print)
Definition at line 6546 of file t_io.c.
References HEADER::category, LONGVECTOR::co, header_scan(), LONGVECTOR::isdynamic, LONGVECTOR::nh, print_header(), skip_whitespaces(), t_error(), and HEADER::type.
long longvectorcmp (LONGVECTOR * A, LONGVECTOR * B)
Definition at line 2873 of file t_io.c.
References LONGVECTOR::co, LONGVECTOR::isdynamic, and LONGVECTOR::nh.
Referenced by read_doublebin(), read_intbin(), read_longbin(), and read_shortbin().
void print_charvector_elements (CHARVECTOR * v, long maxcols)
Definition at line 977 of file t_io.c.
References CHARVECTOR::co, CHARVECTOR::isdynamic, CHARVECTOR::nh, CHARVECTOR::nl, and t_error().
void print_doublebin_elements (DOUBLEBIN * l, long maxcols)
Definition at line 2569 of file t_io.c.
References co, db::co, db::index, db::isdynamic, and t_error().
void print_doublematrix_elements (DOUBLEMATRIX * m, long maxcols)
Definition at line 1844 of file t_io.c.
References DOUBLEMATRIX::co, DOUBLEMATRIX::isdynamic, DOUBLEMATRIX::nch, DOUBLEMATRIX::ncl, DOUBLEMATRIX::nrh, DOUBLEMATRIX::nrl, and t_error().
void print_doubletensor_elements (DOUBLETENSOR * m, long maxcols)
Definition at line 11013 of file t_io.c.
References DOUBLETENSOR::co, DOUBLETENSOR::isdynamic, DOUBLETENSOR::nch, DOUBLETENSOR::ncl, DOUBLETENSOR::ndl, DOUBLETENSOR::nrh, DOUBLETENSOR::nrl, and t_error().
void print_doublevector_elements (DOUBLEVECTOR * v, long maxcols)
Definition at line 826 of file t_io.c.
References DOUBLEVECTOR::co, DOUBLEVECTOR::isdynamic, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, and t_error().
void print_floatmatrix_elements (FLOATMATRIX * m, long maxcols)
Definition at line 1673 of file t_io.c.
References FLOATMATRIX::co, FLOATMATRIX::isdynamic, FLOATMATRIX::nch, FLOATMATRIX::ncl, FLOATMATRIX::nrh, FLOATMATRIX::nrl, and t_error().
void print_floatvector_elements (FLOATVECTOR * v, long maxcols)
Definition at line 675 of file t_io.c.
References FLOATVECTOR::co, FLOATVECTOR::isdynamic, FLOATVECTOR::nh, FLOATVECTOR::nl, and t_error().
void print_header (HEADER * H)
Definition at line 10616 of file t_io.c.
References HEADER::category, t_keywords::category, HEADER::gender, t_keywords::gender, HEADER::name, HEADER::number, T_KEYWORDS, HEADER::type, and t_keywords::type.
Referenced by justread_chararray(), justread_floatarray(), justread_floatmatrix(), justread_longarray(), read_charvector(), read_doublearray(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatarray(), read_floatmatrix(), read_floatvector(), read_intmatrix(), read_intvector(), read_longarray(), read_longmatrix(), read_longvector(), read_shortarray(), read_shortmatrix(), read_shortvector(), and read_stringarray().
void print_intbin_elements (INTBIN * l, long maxcols)
Definition at line 2026 of file t_io.c.
References co, INTBIN::co, INTBIN::index, INTBIN::isdynamic, and t_error().
void print_intmatrix_elements (INTMATRIX * m, long maxcols)
Definition at line 1322 of file t_io.c.
References INTMATRIX::co, INTMATRIX::isdynamic, INTMATRIX::nch, INTMATRIX::ncl, INTMATRIX::nrh, INTMATRIX::nrl, and t_error().
void print_intvector_elements (INTVECTOR * v, long maxcols)
Definition at line 374 of file t_io.c.
References INTVECTOR::co, INTVECTOR::isdynamic, INTVECTOR::nh, INTVECTOR::nl, and t_error().
void print_longbin_elements (LONGBIN * l, long maxcols)
Definition at line 2388 of file t_io.c.
References co, LONGBIN::co, LONGBIN::index, LONGBIN::isdynamic, and t_error().
void print_longmatrix_elements (LONGMATRIX * m, long maxcols)
Definition at line 1496 of file t_io.c.
References LONGMATRIX::co, LONGMATRIX::isdynamic, LONGMATRIX::nch, LONGMATRIX::ncl, LONGMATRIX::nrh, LONGMATRIX::nrl, and t_error().
void print_longvector_elements (LONGVECTOR * v, long maxcols)
Definition at line 525 of file t_io.c.
References LONGVECTOR::co, LONGVECTOR::isdynamic, LONGVECTOR::nh, LONGVECTOR::nl, and t_error().
Referenced by addresses_bubble_sort(), bubble_sort(), print_stringbin_elements(), read_doublebin(), read_intbin(), read_longbin(), and read_shortbin().
void print_shortbin_elements (SHORTBIN * l, long maxcols)
Definition at line 2207 of file t_io.c.
References co, SHORTBIN::co, SHORTBIN::index, SHORTBIN::isdynamic, and t_error().
void print_shortmatrix_elements (SHORTMATRIX * m, long maxcols)
Definition at line 1151 of file t_io.c.
References SHORTMATRIX::co, SHORTMATRIX::isdynamic, SHORTMATRIX::nch, SHORTMATRIX::ncl, SHORTMATRIX::nrh, SHORTMATRIX::nrl, and t_error().
void print_shortvector_elements (SHORTVECTOR * v, long maxcols)
Definition at line 221 of file t_io.c.
References SHORTVECTOR::co, SHORTVECTOR::isdynamic, SHORTVECTOR::nh, SHORTVECTOR::nl, and t_error().
void print_stringbin_elements (STRINGBIN * l, long maxcols)
Definition at line 2797 of file t_io.c.
References co, st::co, st::index, st::isdynamic, print_longvector_elements(), and t_error().
char* query_for_label (FILE * inputfile)
Definition at line 3278 of file t_io.c.
References LABELINCREMENT, MAXLABELSIZE, skip_whitespaces(), and t_error().
Referenced by header_scan(), read_doublebin(), read_intbin(), read_longbin(), and read_shortbin().
int query_for_token (FILE * inputfile, const char * token)
Definition at line 3522 of file t_io.c.
References skip_whitespaces().
Referenced by justread_floatmatrix(), read_charvector(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatmatrix(), read_floatvector(), read_index(), read_intbin(), read_intmatrix(), read_intvector(), read_longbin(), read_longmatrix(), read_longvector(), read_shortbin(), read_shortmatrix(), and read_shortvector().
char* read_buffer_from_stdio (long maxbuffersize)
Definition at line 4256 of file t_io.c.
References BUFFERINCREMENT, and t_error().
CHARVECTOR* read_charvector (FILE * inputfile, char * mode, short print)
Definition at line 6992 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), goto_EOF(), headercmp(), new_charvector(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_charvector_elements(), read_index(), read_vectorheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_charvector_elements (FILE * input, CHARVECTOR * v, char * mode)
It reads a vector of char numbers and returns the number of elements read. Storage mode can be either ascii or binary.
Definition at line 854 of file t_io.c.
References CHARVECTOR::co, CHARVECTOR::isdynamic, CHARVECTOR::nh, CHARVECTOR::nl, and t_error().
Referenced by read_charvector().
int read_comment (FILE * inputfile, int opt, long maxbuffersize, short print)
Definition at line 3571 of file t_io.c.
References BUFFERINCREMENT, iscomment(), and t_error().
Referenced by header_scan(), and read_index().
DOUBLEVECTOR* read_doublearray (FILE * inputfile, short print)
Definition at line 5667 of file t_io.c.
References BUFFERINCREMENT, HEADER::category, DOUBLEVECTOR::co, free_header(), header_scan(), MAXBUFFERSIZE, new_doublevector(), print_header(), skip_whitespaces(), t_error(), and HEADER::type.
Referenced by get_parameter(), get_s_times(), read_b_parameters_ft(), read_connections(), read_doublevector_from_a_ft_format_single_file(), read_map(), read_parameters(), and read_polygon().
DOUBLEBIN* read_doublebin (FILE * inputfile, char * mode, short print)
Definition at line 9919 of file t_io.c.
References EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), free_longvector(), longvectorcmp(), new_doublebin(), NOPRINT, OLD_NAME, OPENYES, print_longvector_elements(), query_for_label(), query_for_token(), read_doublebin_elements(), read_index(), read_longarray(), skip_whitespaces(), t_error(), t_fclose(), and t_fopen().
long read_doublebin_elements (FILE * input, DOUBLEBIN * l, char * mode)
Definition at line 2417 of file t_io.c.
References co, LONGVECTOR::co, db::co, db::index, db::isdynamic, and t_error().
Referenced by read_doublebin().
DOUBLEMATRIX* read_doublematrix (FILE * inputfile, char * mode, short print)
Definition at line 9166 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_doublematrix(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_doublematrix_elements(), read_index(), read_matrixheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
Referenced by read_linevector(), and read_map().
long read_doublematrix_elements (FILE * input, DOUBLEMATRIX * m, char * mode)
Read a matrix of double numbers
Definition at line 1704 of file t_io.c.
References DOUBLEMATRIX::co, DOUBLEMATRIX::isdynamic, DOUBLEMATRIX::nch, DOUBLEMATRIX::ncl, DOUBLEMATRIX::nrh, DOUBLEMATRIX::nrl, and t_error().
Referenced by read_doublematrix().
DOUBLETENSOR* read_doubletensor (FILE * inputfile, char * mode, short print)
Definition at line 11048 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_doubletensor(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_doubletensor_elements(), read_index(), read_matrixheader(), read_tensorheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_doubletensor_elements (FILE * input, DOUBLETENSOR * m, char * mode)
Read a matrix of double numbers
Definition at line 10919 of file t_io.c.
References DOUBLETENSOR::co, DOUBLETENSOR::isdynamic, DOUBLETENSOR::nch, DOUBLETENSOR::ncl, DOUBLETENSOR::ndh, DOUBLETENSOR::ndl, DOUBLETENSOR::nrh, DOUBLETENSOR::nrl, and t_error().
Referenced by read_doubletensor().
DOUBLEVECTOR* read_doublevector (FILE * inputfile, char * mode, short print)
Definition at line 8141 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_doublevector(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_doublevector_elements(), read_index(), read_vectorheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_doublevector_elements (FILE * input, DOUBLEVECTOR * v, char * mode)
It reads a vector of float numbers and returns the number of elements read. Storage mode can be either ascii or binary.
Definition at line 703 of file t_io.c.
References DOUBLEVECTOR::co, DOUBLEVECTOR::isdynamic, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, and t_error().
Referenced by read_doublevector().
STRINGBIN* read_filenames (char * working_directory, char * program, char * extension, char * position)
Definition at line 3230 of file t_io.c.
References st::co, st::index, join_strings(), LONGVECTOR::nh, NOPRINT, read_stringarray(), simplefind(), and t_error().
FLOATVECTOR* read_floatarray (FILE * inputfile, short print)
Definition at line 5344 of file t_io.c.
References BUFFERINCREMENT, HEADER::category, FLOATVECTOR::co, header_scan(), MAXBUFFERSIZE, new_floatvector(), print_header(), skip_whitespaces(), t_error(), and HEADER::type.
FLOATMATRIX* read_floatmatrix (FILE * inputfile, char * mode, short print)
Definition at line 9092 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_floatmatrix(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_floatmatrix_elements(), read_index(), read_matrixheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_floatmatrix_elements (FILE * input, FLOATMATRIX * m, char * mode)
Read a matrix of floating point numbers
Definition at line 1531 of file t_io.c.
References FLOATMATRIX::co, FLOATMATRIX::isdynamic, FLOATMATRIX::nch, FLOATMATRIX::ncl, FLOATMATRIX::nrh, FLOATMATRIX::nrl, and t_error().
Referenced by justread_floatmatrix(), and read_floatmatrix().
FLOATVECTOR* read_floatvector (FILE * inputfile, char * mode, short print)
Definition at line 7909 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_floatvector(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_floatvector_elements(), read_index(), read_vectorheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_floatvector_elements (FILE * input, FLOATVECTOR * v, char * mode)
It reads a vector of float numbers and returns the number of elements read. Storage mode can be either ascii or binary.
Definition at line 553 of file t_io.c.
References FLOATVECTOR::co, FLOATVECTOR::isdynamic, FLOATVECTOR::nh, FLOATVECTOR::nl, and t_error().
Referenced by read_floatvector().
long read_index (FILE * inputfile, short print)
Definition at line 4442 of file t_io.c.
References iscomment(), MAXBUFFERSIZE, query_for_token(), read_comment(), skip_whitespaces(), and t_error().
Referenced by get_filenames_from_keys(), get_s_times(), justread_floatmatrix(), read_b_parameters_ft(), read_charvector(), read_connection_attribute_array(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_doublevector_from_a_ft_format_single_file(), read_fine_indices(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_keywords_list(), read_line_indices(), read_linevector(), read_longbin(), read_longmatrix(), read_longvector(), read_map(), read_polygonvector(), read_shortbin(), read_shortmatrix(), and read_shortvector().
INTBIN* read_intbin (FILE * inputfile, char * mode, short print)
Definition at line 9254 of file t_io.c.
References EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), free_longvector(), goto_EOF(), longvectorcmp(), new_intbin(), NOPRINT, OLD_NAME, OPENYES, print_longvector_elements(), query_for_label(), query_for_token(), read_index(), read_intbin_elements(), read_longarray(), skip_whitespaces(), t_error(), t_fclose(), and t_fopen().
long read_intbin_elements (FILE * input, INTBIN * l, char * mode)
Definition at line 1874 of file t_io.c.
References co, LONGVECTOR::co, INTBIN::co, INTBIN::index, INTBIN::isdynamic, and t_error().
Referenced by read_intbin().
INTMATRIX* read_intmatrix (FILE * inputfile, char * mode, short print)
Definition at line 8618 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_intmatrix(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_index(), read_intmatrix_elements(), read_matrixheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_intmatrix_elements (FILE * input, INTMATRIX * m, char * mode)
Read a matrix of int numbers
Definition at line 1180 of file t_io.c.
References INTMATRIX::co, INTMATRIX::isdynamic, INTMATRIX::nch, INTMATRIX::ncl, INTMATRIX::nrh, INTMATRIX::nrl, and t_error().
Referenced by read_intmatrix().
INTVECTOR* read_intvector (FILE * inputfile, char * mode, short print)
Definition at line 7442 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_intvector(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_index(), read_intvector_elements(), read_vectorheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_intvector_elements (FILE * input, INTVECTOR * v, char * mode)
It reads a vector of short numbers and returns the number of elements read. Storage mode can be either ascii or binary.
Definition at line 249 of file t_io.c.
References INTVECTOR::co, INTVECTOR::isdynamic, INTVECTOR::nh, INTVECTOR::nl, and t_error().
Referenced by read_intvector().
LONGVECTOR* read_longarray (FILE * inputfile, short print)
Definition at line 5023 of file t_io.c.
References BUFFERINCREMENT, HEADER::category, LONGVECTOR::co, header_scan(), MAXBUFFERSIZE, new_longvector(), print_header(), skip_whitespaces(), t_error(), and HEADER::type.
Referenced by read_doublebin(), read_intbin(), read_line_indices(), read_longbin(), and read_shortbin().
LONGBIN* read_longbin (FILE * inputfile, char * mode, short print)
Definition at line 9695 of file t_io.c.
References EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), free_longvector(), longvectorcmp(), new_longbin(), NOPRINT, OLD_NAME, OPENYES, print_longvector_elements(), query_for_label(), query_for_token(), read_index(), read_longarray(), read_longbin_elements(), skip_whitespaces(), t_error(), t_fclose(), and t_fopen().
long read_longbin_elements (FILE * input, LONGBIN * l, char * mode)
Definition at line 2236 of file t_io.c.
References co, LONGVECTOR::co, LONGBIN::co, LONGBIN::index, LONGBIN::isdynamic, and t_error().
Referenced by read_longbin().
LONGMATRIX* read_longmatrix (FILE * inputfile, char * mode, short print)
Definition at line 8856 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_longmatrix(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_index(), read_longmatrix_elements(), read_matrixheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
Referenced by read_fine_indices().
long read_longmatrix_elements (FILE * input, LONGMATRIX * m, char * mode)
Read a matrix of long point numbers
Definition at line 1354 of file t_io.c.
References LONGMATRIX::co, LONGMATRIX::isdynamic, LONGMATRIX::nch, LONGMATRIX::ncl, LONGMATRIX::nrh, LONGMATRIX::nrl, and t_error().
Referenced by read_longmatrix().
LONGVECTOR* read_longvector (FILE * inputfile, char * mode, short print)
Definition at line 7668 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_longvector(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_index(), read_longvector_elements(), read_vectorheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_longvector_elements (FILE * input, LONGVECTOR * v, char * mode)
It reads a vector of long numbers and returns the number of elements read. Storage mode can be either ascii or binary.
Definition at line 402 of file t_io.c.
References LONGVECTOR::co, LONGVECTOR::isdynamic, LONGVECTOR::nh, LONGVECTOR::nl, and t_error().
Referenced by read_longvector().
void read_matrixheader (FILE * inputfile, HEADER * h)
Definition at line 6885 of file t_io.c.
References HEADER::dimensions, header_scan(), skip_whitespaces(), and t_error().
Referenced by justread_floatmatrix(), read_doublematrix(), read_doubletensor(), read_floatmatrix(), read_intmatrix(), read_longmatrix(), and read_shortmatrix().
DOUBLEVECTOR* read_parameters (char * working_directory, char * program, char * extension, char * position)
Definition at line 3255 of file t_io.c.
References join_strings(), NOPRINT, read_doublearray(), simplefind(), and t_error().
STRINGBIN* read_plane_strings (FILE * inputfile, long length, long maxbuffersize)
Definition at line 2602 of file t_io.c.
References BUFFERINCREMENT, LONGVECTOR::co, copy_buffer_into_stringbin(), free_longvector(), new_longvector(), new_stringbin(), LONGVECTOR::nh, skip_whitespaces(), and t_error().
SHORTVECTOR* read_shortarray (FILE * inputfile, short print)
Definition at line 5987 of file t_io.c.
References BUFFERINCREMENT, HEADER::category, SHORTVECTOR::co, header_scan(), MAXBUFFERSIZE, new_shortvector(), print_header(), skip_whitespaces(), t_error(), and HEADER::type.
SHORTBIN* read_shortbin (FILE * inputfile, char * mode, short print)
Definition at line 9472 of file t_io.c.
References EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), free_longvector(), longvectorcmp(), new_shortbin(), NOPRINT, OLD_NAME, OPENYES, print_longvector_elements(), query_for_label(), query_for_token(), read_index(), read_longarray(), read_shortbin_elements(), skip_whitespaces(), t_error(), t_fclose(), and t_fopen().
long read_shortbin_elements (FILE * input, SHORTBIN * l, char * mode)
Definition at line 2055 of file t_io.c.
References co, LONGVECTOR::co, SHORTBIN::co, SHORTBIN::index, SHORTBIN::isdynamic, and t_error().
Referenced by read_shortbin().
SHORTMATRIX* read_shortmatrix (FILE * inputfile, char * mode, short print)
Definition at line 8374 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_shortmatrix(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_index(), read_matrixheader(), read_shortmatrix_elements(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_shortmatrix_elements (FILE * input, SHORTMATRIX * m, char * mode)
Matrixes
 Read a matrix of short numbers
Definition at line 1010 of file t_io.c.
References SHORTMATRIX::co, SHORTMATRIX::isdynamic, SHORTMATRIX::nch, SHORTMATRIX::ncl, SHORTMATRIX::nrh, SHORTMATRIX::nrl, and t_error().
Referenced by read_shortmatrix().
SHORTVECTOR* read_shortvector (FILE * inputfile, char * mode, short print)
Definition at line 7214 of file t_io.c.
References HEADER::category, HEADER::dimensions, EXTERNAL_FILE, EXTERNAL_FILE_NAME, EXTERNAL_FILE_POSITION, free_header(), get_phrase(), headercmp(), new_shortvector(), NOPRINT, OLD_NAME, OPENYES, print_header(), query_for_token(), read_index(), read_shortvector_elements(), read_vectorheader(), skip_whitespaces(), t_error(), t_fclose(), t_fopen(), and HEADER::type.
long read_shortvector_elements (FILE * input, SHORTVECTOR * v, char * mode)
It reads a vector of short numbers and returns the number of elements read. Storage mode can be either ascii or binary.
Definition at line 100 of file t_io.c.
References SHORTVECTOR::co, SHORTVECTOR::isdynamic, SHORTVECTOR::nh, SHORTVECTOR::nl, and t_error().
Referenced by read_shortvector().
STRINGBIN* read_stringarray (FILE * inputfile, short print)
Definition at line 6090 of file t_io.c.
References BUFFERINCREMENT, HEADER::category, co, LONGVECTOR::co, st::co, free_header(), header_scan(), st::index, MAXBUFFERSIZE, new_longvector(), new_stringbin(), print_header(), skip_whitespaces(), t_error(), and HEADER::type.
Referenced by get_filename(), get_s_times(), get_strings(), read_filenames(), and read_keywords().
void read_tensorheader (FILE * inputfile, HEADER * h)
Definition at line 11145 of file t_io.c.
References HEADER::dimensions, header_scan(), skip_whitespaces(), and t_error().
Referenced by read_doubletensor().
void read_vectorheader (FILE * inputfile, HEADER * h)
Definition at line 6769 of file t_io.c.
References HEADER::dimensions, header_scan(), skip_whitespaces(), and t_error().
Referenced by read_charvector(), read_doublevector(), read_floatvector(), read_intvector(), read_longvector(), and read_shortvector().
char* readandstore_comment (FILE * inputfile, int opt, long maxbuffersize)
Definition at line 3921 of file t_io.c.
References BUFFERINCREMENT, iscomment(), and t_error().
void skip_whitespaces (FILE * inputfile)
Definition at line 2909 of file t_io.c.
Referenced by file_copy(), get_phrase(), header_scan(), iscomment(), justread_chararray(), justread_floatarray(), justread_floatmatrix(), justread_longarray(), query_for_label(), query_for_token(), read_charvector(), read_doublearray(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatarray(), read_floatmatrix(), read_floatvector(), read_index(), read_intbin(), read_intmatrix(), read_intvector(), read_longarray(), read_longbin(), read_longmatrix(), read_longvector(), read_matrixheader(), read_plane_strings(), read_plane_strings_restricted(), read_shortarray(), read_shortbin(), read_shortmatrix(), read_shortvector(), read_stringarray(), read_tensorheader(), and read_vectorheader().
FILE* t_fclose (FILE * stream)
Definition at line 81 of file t_io.c.
Referenced by doublematrix_control(), doublematrix_dem(), doublematrix_dem2(), doublematrix_dem3(), doubletensor_dem(), doublevector_dem(), floatmatrix_dem(), floatmatrix_dem2(), floatvector_dem(), get_filename(), get_filenames_from_keys(), get_parameter(), get_s_times(), get_strings(), intmatrix_dem(), intmatrix_dem2(), justread_floatmatrix(), longmatrix_dem(), longmatrix_dem2(), read_b_parameters_ft(), read_charvector(), read_connection_attribute_array(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_fine_indices(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_keywords_list(), read_line_indices(), read_longbin(), read_longmatrix(), read_longvector(), read_map(), read_polygonvector(), read_shortbin(), read_shortmatrix(), read_shortvector(), shortmatrix_dem(), shortmatrix_dem2(), shortmatrix_dem3(), write_doublevector_in_a_ascii_ft_format_single_file(), write_fluidturtle(), write_longmatrix_vector(), and write_small_lines_indices().
FILE* t_fopen (const char * name, const char * mode)
Definition at line 45 of file t_io.c.
References t_error().
Referenced by doublematrix_control(), doublematrix_dem(), doublematrix_dem2(), doublematrix_dem3(), doubletensor_dem(), doublevector_dem(), floatmatrix_dem(), floatmatrix_dem2(), floatvector_dem(), get_filenames_from_keys(), get_s_times(), intmatrix_dem(), intmatrix_dem2(), justread_floatmatrix(), longmatrix_dem(), longmatrix_dem2(), read_b_parameters_ft(), read_charvector(), read_connection_attribute_array(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_fine_indices(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_keywords_list(), read_line_indices(), read_linevector(), read_longbin(), read_longmatrix(), read_longvector(), read_map(), read_polygonvector(), read_shortbin(), read_shortmatrix(), read_shortvector(), shortmatrix_dem(), shortmatrix_dem2(), shortmatrix_dem3(), write_doublevector_in_a_ascii_ft_format_single_file(), write_fluidturtle(), write_longmatrix_vector(), and write_small_lines_indices().
void write_chararray_elements (FILE * outputfile, CHARVECTOR * V, long columns)
Definition at line 10485 of file t_io.c.
References CHARVECTOR::co, CHARVECTOR::isdynamic, CHARVECTOR::nh, CHARVECTOR::nl, and t_error().
long write_charvector_elements (FILE * output, CHARVECTOR * v, long maxcols)
 Write a vector of char to a file
Definition at line 900 of file t_io.c.
References CHARVECTOR::co, CHARVECTOR::isdynamic, CHARVECTOR::nh, CHARVECTOR::nl, OK, and t_error().
void write_comment (FILE * outputfile, const char * comment, long columns)
Definition at line 10796 of file t_io.c.
References t_error().
void write_doublearray_elements (FILE * outputfile, DOUBLEVECTOR * V, long columns)
Definition at line 10417 of file t_io.c.
References DOUBLEVECTOR::co, DOUBLEVECTOR::isdynamic, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, and t_error().
Referenced by doublematrix_dem2(), doublematrix_dem3(), doubletensor_dem(), doublevector_dem(), longmatrix_dem2(), shortmatrix_dem2(), and shortmatrix_dem3().
long write_doublebin_elements (FILE * output, DOUBLEBIN * l, long maxcols)
 Write a list of double to a file
Definition at line 2484 of file t_io.c.
References co, LONGVECTOR::co, db::co, db::index, db::isdynamic, OK, and t_error().
long write_doublematrix_elements (FILE * output, DOUBLEMATRIX * m, long maxcols)
Definition at line 1764 of file t_io.c.
References DOUBLEMATRIX::co, DOUBLEMATRIX::isdynamic, DOUBLEMATRIX::nch, DOUBLEMATRIX::ncl, DOUBLEMATRIX::nrh, DOUBLEMATRIX::nrl, OK, and t_error().
Referenced by doublematrix_control(), doublematrix_dem(), doublematrix_dem2(), doublematrix_dem3(), and doubletensor_dem().
long write_doubletensor_elements (FILE * output, DOUBLETENSOR * m, long maxcols)
Definition at line 10971 of file t_io.c.
References DOUBLETENSOR::co, DOUBLETENSOR::isdynamic, DOUBLETENSOR::nch, DOUBLETENSOR::ncl, DOUBLETENSOR::ndh, DOUBLETENSOR::ndl, DOUBLETENSOR::nrh, DOUBLETENSOR::nrl, OK, and t_error().
long write_doublevector_elements (FILE * output, DOUBLEVECTOR * v, long maxcols)
 Write a vector of double to a file
Definition at line 749 of file t_io.c.
References DOUBLEVECTOR::co, DOUBLEVECTOR::isdynamic, DOUBLEVECTOR::nh, DOUBLEVECTOR::nl, OK, and t_error().
void write_floatarray_elements (FILE * outputfile, FLOATVECTOR * V, long columns)
Definition at line 10351 of file t_io.c.
References FLOATVECTOR::co, FLOATVECTOR::isdynamic, FLOATVECTOR::nh, FLOATVECTOR::nl, and t_error().
Referenced by doublematrix_dem(), floatmatrix_dem(), floatmatrix_dem2(), floatvector_dem(), intmatrix_dem(), intmatrix_dem2(), longmatrix_dem(), and shortmatrix_dem().
long write_floatmatrix_elements (FILE * output, FLOATMATRIX * m, long maxcols)
Definition at line 1595 of file t_io.c.
References FLOATMATRIX::co, FLOATMATRIX::isdynamic, FLOATMATRIX::nch, FLOATMATRIX::ncl, FLOATMATRIX::nrh, FLOATMATRIX::nrl, OK, and t_error().
Referenced by floatmatrix_dem(), and floatmatrix_dem2().
long write_floatvector_elements (FILE * output, FLOATVECTOR * v, long maxcols)
 Write a vector of float to a file
Definition at line 599 of file t_io.c.
References FLOATVECTOR::co, FLOATVECTOR::isdynamic, FLOATVECTOR::nh, FLOATVECTOR::nl, OK, and t_error().
void write_header_header (FILE * outputfile, HEADER * H)
Definition at line 10654 of file t_io.c.
References HEADER::category, t_keywords::category, t_keywords::delimiter, HEADER::dimensions, HEADER::gender, t_keywords::gender, HEADER::name, HEADER::number, t_error(), HEADER::type, and t_keywords::type.
void write_intarray_elements (FILE * outputfile, INTVECTOR * V, long columns)
Definition at line 10213 of file t_io.c.
References INTVECTOR::co, INTVECTOR::isdynamic, INTVECTOR::nh, INTVECTOR::nl, and t_error().
long write_intbin_elements (FILE * output, INTBIN * l, long maxcols)
 Write a list of int to a file
Definition at line 1941 of file t_io.c.
References co, LONGVECTOR::co, INTBIN::co, INTBIN::index, INTBIN::isdynamic, OK, and t_error().
long write_intmatrix_elements (FILE * output, INTMATRIX * m, long maxcols)
Definition at line 1244 of file t_io.c.
References INTMATRIX::co, INTMATRIX::isdynamic, INTMATRIX::nch, INTMATRIX::ncl, INTMATRIX::nrh, INTMATRIX::nrl, OK, and t_error().
Referenced by intmatrix_dem(), and intmatrix_dem2().
long write_intvector_elements (FILE * output, INTVECTOR * v, long maxcols)
 Write a vector of int to a file
Definition at line 296 of file t_io.c.
References INTVECTOR::co, INTVECTOR::isdynamic, INTVECTOR::nh, INTVECTOR::nl, OK, and t_error().
void write_longarray_elements (FILE * outputfile, LONGVECTOR * V, long columns)
Definition at line 10283 of file t_io.c.
References LONGVECTOR::co, LONGVECTOR::isdynamic, LONGVECTOR::nh, LONGVECTOR::nl, and t_error().
long write_longbin_elements (FILE * output, LONGBIN * l, long maxcols)
 Write a list of int to a file
Definition at line 2303 of file t_io.c.
References co, LONGVECTOR::co, LONGBIN::co, LONGBIN::index, LONGBIN::isdynamic, OK, and t_error().
long write_longmatrix_elements (FILE * output, LONGMATRIX * m, long maxcols)
Definition at line 1417 of file t_io.c.
References LONGMATRIX::co, LONGMATRIX::isdynamic, LONGMATRIX::nch, LONGMATRIX::ncl, LONGMATRIX::nrh, LONGMATRIX::nrl, OK, and t_error().
Referenced by longmatrix_dem(), longmatrix_dem2(), and write_longmatrix_vector().
long write_longvector_elements (FILE * output, LONGVECTOR * v, long maxcols)
 Write a vector of int to a file
Definition at line 448 of file t_io.c.
References LONGVECTOR::co, LONGVECTOR::isdynamic, LONGVECTOR::nh, LONGVECTOR::nl, OK, and t_error().
void write_shortarray_elements (FILE * outputfile, SHORTVECTOR * V, long columns)
Definition at line 10145 of file t_io.c.
References SHORTVECTOR::co, SHORTVECTOR::isdynamic, SHORTVECTOR::nh, SHORTVECTOR::nl, and t_error().
long write_shortbin_elements (FILE * output, SHORTBIN * l, long maxcols)
 Write a list of int to a file
Definition at line 2122 of file t_io.c.
References co, LONGVECTOR::co, SHORTBIN::co, SHORTBIN::index, SHORTBIN::isdynamic, OK, and t_error().
long write_shortmatrix_elements (FILE * output, SHORTMATRIX * m, long maxcols)
Definition at line 1071 of file t_io.c.
References SHORTMATRIX::co, SHORTMATRIX::isdynamic, SHORTMATRIX::nch, SHORTMATRIX::ncl, SHORTMATRIX::nrh, SHORTMATRIX::nrl, OK, and t_error().
Referenced by shortmatrix_dem(), shortmatrix_dem2(), and shortmatrix_dem3().
long write_shortvector_elements (FILE * output, SHORTVECTOR * v, long maxcols)
 Write a vector of short int to a file
Definition at line 146 of file t_io.c.
References SHORTVECTOR::co, SHORTVECTOR::isdynamic, SHORTVECTOR::nh, SHORTVECTOR::nl, OK, and t_error().
long write_stringbin_elements (FILE * output, STRINGBIN * l, long maxcols)
 Write a list of strings to a file
Definition at line 2758 of file t_io.c.
References co, LONGVECTOR::co, st::co, st::index, st::isdynamic, OK, and t_error().
void write_stringsarray_elements (FILE * outputfile, STRINGBIN * V)
Definition at line 10551 of file t_io.c.
References st::co, st::index, st::isdynamic, and t_error().
void write_turtle (FILE * outputfile, char * creator, char * inputs)
Definition at line 10738 of file t_io.c.
References t_error().
Variable Documentation
FILE* EXTERNAL_FILE
Definition at line 9 of file t_io.c.
Referenced by justread_floatmatrix(), read_charvector(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_longbin(), read_longmatrix(), read_longvector(), read_shortbin(), read_shortmatrix(), and read_shortvector().
char EXTERNAL_FILE_NAME[256]
Definition at line 13 of file t_io.c.
Referenced by justread_floatmatrix(), read_charvector(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_longbin(), read_longmatrix(), read_longvector(), read_shortbin(), read_shortmatrix(), and read_shortvector().
long int EXTERNAL_FILE_POSITION =SEEK_SET
Definition at line 15 of file t_io.c.
Referenced by justread_floatmatrix(), read_charvector(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_longbin(), read_longmatrix(), read_longvector(), read_shortbin(), read_shortmatrix(), and read_shortvector().
HEADER EXTERNAL_HEADER
Definition at line 17 of file t_io.c.
LONGVECTOR* EXTERNAL_P
Definition at line 11 of file t_io.c.
long IO_FILES_COUNTER =0
Definition at line 23 of file t_io.c.
Referenced by get_filename(), and get_strings().
long IO_PARMS_COUNTER =0
Definition at line 26 of file t_io.c.
Referenced by get_parameter().
long IO_STRINGS_COUNTER =0
Definition at line 24 of file t_io.c.
char OLD_NAME[256]
Definition at line 13 of file t_io.c.
Referenced by justread_floatmatrix(), read_charvector(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_longbin(), read_longmatrix(), read_longvector(), read_shortbin(), read_shortmatrix(), and read_shortvector().
short OPENYES =0
Definition at line 21 of file t_io.c.
Referenced by justread_floatmatrix(), read_charvector(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_longbin(), read_longmatrix(), read_longvector(), read_shortbin(), read_shortmatrix(), and read_shortvector().
t_keywords T_KEYWORDS
Initial value:
={{"2","ascii","binary"},
                                                          {"7","char","short","int","long","float","double"
      ,"string"},
                                                          {"5","array","vector","matrix","list","tensor"},
                                                          {"2","->","<-"},
                                                          {"2"," ",","},
                                                          {"2","{","}"}}
Definition at line 29 of file t_io.c.
Referenced by header_scan(), print_header(), and search_array().
char* WORKING_DIRECTORY ='\0'
Definition at line 5 of file t_io.c.
Referenced by doublematrix_control(), doublematrix_dem(), doublematrix_dem3(), doubletensor_dem(), doublevector_dem(), floatmatrix_dem(), floatvector_dem(), get_phrase(), intmatrix_dem(), longmatrix_dem(), shortmatrix_dem(), and shortmatrix_dem3().
long WORKING_POSITION =0
Definition at line 25 of file t_io.c.
Referenced by get_filename(), get_parameter(), and get_strings().