FLUIDTURTLES/t_random.h File Reference
Functions
long urand (long *, long)
double ran1 (long *)
double ran2 (long *)
double ran3 (long *)
double uuvel (float vmed, float vvar)
double gasdev (long *idum)
Function Documentation
double gasdev (long * idum)
Definition at line 267 of file random.c.
References ran1().
Referenced by uuvel().
double ran1 (long *)
Definition at line 75 of file random.c.
References IA1, IA2, IA3, IC1, IC2, IC3, M1, M2, M3, RM1, RM2, and t_error().
Referenced by gasdev().
double ran2 (long *)
Definition at line 112 of file random.c.
References AM1, IAA1, IAA2, IM1, IM2, IMM1, IQ1, IQ2, IR1, IR2, NDIV, NTAB, and RNMX.
double ran3 (long *)
Definition at line 156 of file random.c.
References AM, IA, IM, IQ, IR, NDIV, NTAB, and RNMX.
Referenced by bnldev(), expdev(), and poisdev().
long urand (long * , long)
Name:
Synopsis:
Version: 1.0
Description:
Authors & Date: Riccardo Rigon, 1998
FILE: LIBRARIES/BASICS/t_random.h, LIBRARIES/BASICS/random.c
Inputs:
Return:
See Also:
Keywords:
Examples: 1.example.c, 2.example.c
Definition at line 45 of file random.c.
double uuvel (float vmed, float vvar)
Definition at line 251 of file random.c.
References gasdev().