ASCII/tabs.h File Reference
Macros
#define end_vector -9.0E+5
#define end_vector_long 999999
Functions
char ** readline_textarray (FILE *f, long offset)
void readline_array (FILE *f, double *a, long offset, long ncol, double ndef, short *endoffile)
double decod (char *ch, long n, double ndef)
long dim1 (double *a)
long dim1l (long *a)
long dim2 (double **a)
long dim_string (char *a)
long dim_vect_strings (char **a)
double ** alloc2 (long n, long m)
double * alloc1 (long n)
long ** alloc_long2 (long n)
long * alloc_long1 (long n)
short compare_strings (char *a, char *b)
Macro Definition Documentation
#define end_vector -9.0E+5
Definition at line 26 of file tabs.h.
Referenced by alloc1(), alloc2(), dim1(), and dim2().
#define end_vector_long 999999
Definition at line 27 of file tabs.h.
Referenced by alloc_long1(), alloc_long2(), and dim1l().
Function Documentation
double* alloc1 (long n)
Definition at line 327 of file tabs.c.
References end_vector.
double** alloc2 (long n, long m)
Definition at line 314 of file tabs.c.
References end_vector.
long* alloc_long1 (long n)
Definition at line 349 of file tabs.c.
References end_vector_long.
long** alloc_long2 (long n)
Definition at line 338 of file tabs.c.
References end_vector_long.
short compare_strings (char * a, char * b)
Definition at line 364 of file tabs.c.
References dim_string().
double decod (char * ch, long n, double ndef)
Definition at line 218 of file tabs.c.
References t_error().
Referenced by readline_array().
long dim1 (double * a)
Definition at line 280 of file tabs.c.
References end_vector.
long dim1l (long * a)
Definition at line 286 of file tabs.c.
References end_vector_long.
long dim2 (double ** a)
Definition at line 292 of file tabs.c.
References end_vector.
long dim_string (char * a)
Definition at line 298 of file tabs.c.
Referenced by compare_strings().
long dim_vect_strings (char ** a)
Definition at line 304 of file tabs.c.
void readline_array (FILE * f, double * a, long offset, long ncol, double ndef, short * endoffile)
Definition at line 134 of file tabs.c.
References decod(), and t_error().
char** readline_textarray (FILE * f, long offset)
Definition at line 39 of file tabs.c.
References t_error().