FLUIDTURTLES/tensors3D.c File Reference
#include `turtle.h`
*
#include `tensor3D.h`
*
Functions
double *** d3tensor (long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
DOUBLETENSOR * new_doubletensor (long ndh, long nrh, long nch)
void free_d3tensor (double ***t, long ndl, long nrl, long ncl)
void free_doubletensor (DOUBLETENSOR *m)
void initialize_doubletensor (DOUBLETENSOR *L, double sign)
Function Documentation
double*** d3tensor (long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
Definition at line 9 of file tensors3D.c.
References NR_END, and t_error().
Referenced by new_doubletensor().
void free_d3tensor (double *** t, long ndl, long nrl, long ncl)
Definition at line 83 of file tensors3D.c.
References FREE_ARG, and NR_END.
Referenced by free_doubletensor().
void free_doubletensor (DOUBLETENSOR * m)
Definition at line 97 of file tensors3D.c.
References DOUBLETENSOR::co, free_d3tensor(), DOUBLETENSOR::isdynamic, DOUBLETENSOR::nch, DOUBLETENSOR::ncl, DOUBLETENSOR::ndh, DOUBLETENSOR::ndl, NL, DOUBLETENSOR::nrh, DOUBLETENSOR::nrl, and t_error().
void initialize_doubletensor (DOUBLETENSOR * L, double sign)
Definition at line 123 of file tensors3D.c.
References DOUBLETENSOR::co, DOUBLETENSOR::isdynamic, DOUBLETENSOR::nch, DOUBLETENSOR::ndh, DOUBLETENSOR::nrh, and t_error().
Referenced by build_frommatrix().
DOUBLETENSOR* new_doubletensor (long ndh, long nrh, long nch)
Definition at line 53 of file tensors3D.c.
References DOUBLETENSOR::co, d3tensor(), isDynamic, DOUBLETENSOR::isdynamic, DOUBLETENSOR::nch, DOUBLETENSOR::ncl, DOUBLETENSOR::ndh, DOUBLETENSOR::ndl, NL, DOUBLETENSOR::nrh, DOUBLETENSOR::nrl, and t_error().
Referenced by build_frommatrix(), linear_span_doubletensor(), and read_doubletensor().