FLUIDTURTLES/turtle.h File Reference
#include <stdio.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include <time.h>
*
#include <ctype.h>
*
#include `t_alloc.h`
*
#include `t_io.h`
*
#include `t_list.h`
*
Data Structures
struct FLOATVECTOR
struct INTVECTOR
struct LONGVECTOR
struct SHORTVECTOR
struct DOUBLEVECTOR
struct CHARVECTOR
struct SHORTMATRIX
struct INTMATRIX
struct FLOATMATRIX
struct DOUBLEMATRIX
struct LONGMATRIX
struct SHORTBIN
struct INTBIN
struct LONGBIN
struct FLOATBIN
struct db
struct st
struct DOUBLETENSOR
struct HEADER
struct t_keywords
struct T_INIT
Macros
#define isDynamic
#define MAXBUFFERSIZE
#define MAXLABELSIZE 1024 /* The same as above */
#define BUFFERINCREMENT
#define LABELINCREMENT 64 /*The same as above */
#define NR_END
#define FREE_ARG char* /* The same as above */
#define OK 1
#define NOK -1
#define WOK 0
#define MAX_KEYWORD_LENGTH 8
#define PRINT 1
#define NOPRINT
#define NL
#define TEST 1
#define NOTEST 0
#define SQRT2 1.414213562373095
#define co
Typedefs
typedef struct db DOUBLEBIN
typedef struct st STRINGBIN
Functions
void t_error (char *error_text)
Macro Definition Documentation
#define BUFFERINCREMENT
Value:
/*Buffers memory is increases when necessary of this
                                                         storage capability till MAXBUFFERSIZE*/
Definition at line 19 of file turtle.h.
Referenced by read_buffer_from_stdio(), read_comment(), read_doublearray(), read_floatarray(), read_longarray(), read_plane_strings(), read_plane_strings_restricted(), read_shortarray(), read_stringarray(), and readandstore_comment().
#define co
Value:
element /* The "co" pointer within MATRIX, TENSOR and VECTOR structs contains the string or numerical
       elements of
                                        matrices, tensors and vectors, the word "co" can be replaced with
       "element" as previously utilized */
Definition at line 74 of file turtle.h.
Referenced by copy_buffer_into_stringbin(), esponentialsplit(), esponentialsplit2realvectors(), interpolate(), new_doublebin(), new_intbin(), new_longbin(), new_shortbin(), new_stringbin(), print_doublebin_elements(), print_intbin_elements(), print_longbin_elements(), print_shortbin_elements(), print_stringbin_elements(), read_doublebin_elements(), read_intbin_elements(), read_longbin_elements(), read_shortbin_elements(), read_stringarray(), sort2floatvectors(), sort2realvectors(), sort2vectors(), sortreal(), split(), split2realvectors(), write_doublebin_elements(), write_intbin_elements(), write_longbin_elements(), write_shortbin_elements(), and write_stringbin_elements().
#define FREE_ARG char* /* The same as above */
Definition at line 32 of file turtle.h.
Referenced by free_charmatrix(), free_cvector(), free_d3tensor(), free_dmatrix(), free_doublebin(), free_dvector(), free_imatrix(), free_intbin(), free_ivector(), free_lmatrix(), free_longbin(), free_lvector(), free_matrix(), free_shortbin(), free_smatrix(), free_stringbin(), free_svector(), and free_vector().
#define isDynamic
Value:
        /*This number will be used to mark a dynamic allocates
                              quantity */
Definition at line 9 of file turtle.h.
Referenced by esponentialsplit(), new_charvector(), new_connection_attributes(), new_doublebin(), new_doublematrix(), new_doubletensor(), new_doublevector(), new_floatmatrix(), new_floatvector(), new_intbin(), new_intmatrix(), new_intvector(), new_linevector(), new_longbin(), new_longmatrix(), new_longvector(), new_polygonvector(), new_shortbin(), new_shortmatrix(), new_shortvector(), new_stringbin(), read_keywords_list(), reorder_keywords_list(), and split().
#define LABELINCREMENT 64 /*The same as above */
Definition at line 23 of file turtle.h.
Referenced by get_phrase(), and query_for_label().
#define MAX_KEYWORD_LENGTH 8
Definition at line 48 of file turtle.h.
Referenced by header_scan().
#define MAXBUFFERSIZE
Value:
/* Many functions uses a buffer to allocate data. A
                             safe habit is to limit its size. */
Definition at line 12 of file turtle.h.
Referenced by header_scan(), read_doublearray(), read_floatarray(), read_index(), read_longarray(), read_shortarray(), and read_stringarray().
#define MAXLABELSIZE 1024 /* The same as above */
Definition at line 16 of file turtle.h.
Referenced by get_phrase(), and query_for_label().
#define NL
Value:
             /* Numerical Recipes allocation routines allow to have
                                                         arbitrary subscripts for vector and matrixes. The
                                                         fluid turtle library restrict this freedom by
       setting
                                                     their lower value to NL */
Definition at line 58 of file turtle.h.
Referenced by bubble_sort_elevation_in_longbin(), fprint_polygonconnectionattributearray(), fprint_polygonvector(), free_charvector(), free_doublematrix(), free_doubletensor(), free_doublevector(), free_floatmatrix(), free_floatvector(), free_intmatrix(), free_intvector(), free_longmatrix(), free_longvector(), free_shortmatrix(), free_shortvector(), min_elevation(), new_charvector(), new_connection_attributes(), new_doublematrix(), new_doubletensor(), new_doublevector(), new_floatmatrix(), new_floatvector(), new_intmatrix(), new_intvector(), new_linevector(), new_longbin_from_doublematrix_array(), new_longbin_from_longbin(), new_longbin_from_longbin_cleaning_novalues(), new_longmatrix(), new_longmatrix_vector(), new_longvector(), new_polygonvector(), new_raster_map(), new_shortmatrix(), new_shortvector(), q_discharge_from_outlet_subs_line(), read_keywords_list(), vertical_area_subs(), vertical_area_surf(), volume_subs(), volume_surf(), wet_area(), write_polygonconnectionattributearray(), write_polygonvector(), and write_small_lines_indices().
#define NOK -1
Definition at line 40 of file turtle.h.
#define NOPRINT
Value:
        /*With the above PRINT is used to set a printint option
                           in some functions */
Definition at line 54 of file turtle.h.
Referenced by aggregate(), get_filename(), get_parameter(), get_strings(), header_scan(), justread_floatmatrix(), read_charvector(), read_doublebin(), read_doublematrix(), read_doubletensor(), read_doublevector(), read_filenames(), read_floatmatrix(), read_floatvector(), read_intbin(), read_intmatrix(), read_intvector(), read_longbin(), read_longmatrix(), read_longvector(), read_parameters(), read_shortbin(), read_shortmatrix(), and read_shortvector().
#define NOTEST 0
Definition at line 68 of file turtle.h.
#define NR_END
Value:
        /* Required by the Numerical Recipes' allocation routines
                                                        */
Definition at line 27 of file turtle.h.
#define OK 1
Definition at line 36 of file turtle.h.
Referenced by copy_buffer_into_stringbin(), header_scan(), write_charvector_elements(), write_doublebin_elements(), write_doublematrix_elements(), write_doubletensor_elements(), write_doublevector_elements(), write_floatmatrix_elements(), write_floatvector_elements(), write_intbin_elements(), write_intmatrix_elements(), write_intvector_elements(), write_longbin_elements(), write_longmatrix_elements(), write_longvector_elements(), write_shortbin_elements(), write_shortmatrix_elements(), write_shortvector_elements(), and write_stringbin_elements().
#define PRINT 1
Definition at line 52 of file turtle.h.
#define SQRT2 1.414213562373095
Definition at line 71 of file turtle.h.
#define TEST 1
Definition at line 65 of file turtle.h.
#define WOK 0
Definition at line 44 of file turtle.h.
Typedef Documentation
typedef struct db DOUBLEBIN
typedef struct st STRINGBIN
Function Documentation
void t_error (char * error_text)
Definition at line 5 of file error.c.
Referenced by assignnovalue(), binarywrite_charvector_elements(), binarywrite_doublebin_elements(), binarywrite_doublematrix_elements(), binarywrite_doublevector_elements(), binarywrite_floatmatrix_elements(), binarywrite_floatvector_elements(), binarywrite_intbin_elements(), binarywrite_intmatrix_elements(), binarywrite_intvector_elements(), binarywrite_longbin_elements(), binarywrite_longmatrix_elements(), binarywrite_longvector_elements(), binarywrite_shortbin_elements(), binarywrite_shortmatrix_elements(), binarywrite_shortvector_elements(), buffer2list(), build_doubletensor(), build_frommatrix(), charmatrix(), clean_floatmatrix(), convlv(), copy_buffer_into_stringbin(), copy_doublematrix(), copy_doublevector(), copy_floatmatrix(), copy_floatvector(), copy_intmatrix(), copy_intvector(), copy_longmatrix(), copy_longvector(), copy_shortmatrix(), copy_shortvector(), cvector(), d3tensor(), decod(), delete_ijx(), delete_ix(), delete_longpair(), delete_longpoker(), delete_realpair(), delete_xyz(), deleteshuffle_longpair(), dmatrix(), double_n_moment(), doublematrix_element_multiplication(), doublematrix_n_moment(), doublevector_correlation(), doublevector_element_multiplication(), doublevector_n_moment(), dsprsax(), dsprstx(), dvector(), error_message(), esponentialsplit(), esponentialsplit2realvectors(), exponentialhystogram(), extract_doublematrix(), extract_fromtensor(), file_copy(), floatmatrix_element_multiplication(), floatmatrix_n_moment(), floatmatrix_restricted_n_moment(), floatvector_correlation(), floatvector_element_multiplication(), floatvector_n_moment(), fmultiplydoublematrix(), free_charvector(), free_doublebin(), free_doublematrix(), free_doubletensor(), free_doublevector(), free_floatmatrix(), free_floatvector(), free_intbin(), free_intmatrix(), free_intvector(), free_longbin(), free_longmatrix(), free_longvector(), free_shortbin(), free_shortmatrix(), free_shortvector(), free_stringbin(), get_doubleraster_map(), get_doublesquare_grid(), get_filename(), get_fine_indices(), get_parameter(), get_phrase(), get_s_times(), get_square_grid(), get_strings(), get_workingdirectory(), header_scan(), headercmp(), imatrix(), initialize_doublematrix(), initialize_doubletensor(), initialize_doublevector(), initialize_floatmatrix(), initialize_floatvector(), initialize_longmatrix(), initialize_longvector(), initialize_shortmatrix(), initialize_shortvector(), interpolate(), interpolate_doublematrix(), interpolate_floatmatrix(), ivector(), join_3strings_into(), join_strings_into(), justread_chararray(), justread_floatarray(), justread_floatmatrix(), justread_longarray(), linear_span_doubletensor(), lmatrix(), longmatrix_element_multiplication(), longmatrix_n_moment(), longvector_correlation(), longvector_element_multiplication(), longvector_n_moment(), lvector(), main(), matrix(), new_charvector(), new_connection_attributes(), new_doublebin(), new_doublematrix(), new_doubletensor(), new_doublevector(), new_floatmatrix(), new_floatvector(), new_ijx(), new_intbin(), new_intmatrix(), new_intvector(), new_ix(), new_line_from_points(), new_linevector(), new_longbin(), new_longmatrix(), new_longmatrix_vector(), new_longpair(), new_longpoker(), new_longvector(), new_output_filenames(), new_point(), new_polygon_from_a_linevector(), new_polygonvector(), new_raster_map(), new_realpair(), new_shortbin(), new_shortmatrix(), new_shortvector(), new_stringbin(), new_word(), new_xyz(), point2ijx(), point2ix(), point2longpair(), point2longpoker(), point2measure(), point2realpair(), print_charvector_elements(), print_doublebin_elements(), print_doublematrix_elements(), print_doubletensor_elements(), print_doublevector_elements(), print_floatmatrix_elements(), print_floatvector_elements(), print_intbin_elements(), print_intmatrix_elements(), print_intvector_elements(), print_longbin_elements(), print_longmatrix_elements(), print_longvector_elements(), print_shortbin_elements(), print_shortmatrix_elements(), print_shortvector_elements(), print_stringbin_elements(), prod_doublematvet(), prodscal(), query_for_label(), ran1(), read_b_parameters_ft(), read_buffer_from_stdio(), read_charvector(), read_charvector_elements(), read_comment(), read_doublearray(), read_doublebin(), read_doublebin_elements(), read_doublematrix(), read_doublematrix_elements(), read_doublesquare_grid(), read_doubletensor(), read_doubletensor_elements(), read_doublevector(), read_doublevector_elements(), read_esriascii(), read_filenames(), read_fine_indices(), read_floatarray(), read_floatmatrix(), read_floatmatrix_elements(), read_floatvector(), read_floatvector_elements(), read_grassascii(), read_grid(), read_index(), read_intbin(), read_intbin_elements(), read_intmatrix(), read_intmatrix_elements(), read_intvector(), read_intvector_elements(), read_keywords(), read_keywords_list(), read_longarray(), read_longbin(), read_longbin_elements(), read_longmatrix(), read_longmatrix_elements(), read_longvector(), read_longvector_elements(), read_map(), read_maptensor(), read_matrixheader(), read_parameters(), read_plane_strings(), read_plane_strings_restricted(), read_polygon(), read_shortarray(), read_shortbin(), read_shortbin_elements(), read_shortmatrix(), read_shortmatrix_elements(), read_shortvector(), read_shortvector_elements(), read_square_grid(), read_stringarray(), read_tensor(), read_tensorheader(), read_vectorheader(), readandstore_comment(), readline_array(), readline_textarray(), realbuffer2list(), realpair_into_doublematrix(), reorder_keywords_list(), search_array(), search_named_array(), shortmatrix_element_multiplication(), shortvector_element_multiplication(), simplefind(), simplehystogram(), smatrix(), split(), split2realvectors(), sprsin(), ssimplefindkeyword(), svector(), t_fopen(), tridiag(), vector(), vectorize_doublematrix(), vectorize_floatmatrix(), vectorize_longmatrix(), vectorize_shortmatrix(), write_chararray_elements(), write_charvector_elements(), write_comment(), write_doublearray_elements(), write_doublebin_elements(), write_doublematrix_elements(), write_doubletensor_elements(), write_doublevector_elements(), write_esriascii(), write_floatarray_elements(), write_floatmatrix_elements(), write_floatvector_elements(), write_frommatrix(), write_header_header(), write_intarray_elements(), write_intbin_elements(), write_intmatrix_elements(), write_intvector_elements(), write_longarray_elements(), write_longbin_elements(), write_longmatrix_elements(), write_longvector_elements(), write_read_filenames(), write_shortarray_elements(), write_shortbin_elements(), write_shortmatrix_elements(), write_shortvector_elements(), write_stringbin_elements(), write_stringsarray_elements(), write_suffix(), write_turtle(), and xyz_into_doublematrix().