MATH2/util_math.h File Reference
Functions
void tridiag (short a, long r, long c, long nx, DOUBLEVECTOR *diag_inf, DOUBLEVECTOR *diag, DOUBLEVECTOR *diag_sup, DOUBLEVECTOR *b, DOUBLEVECTOR *e)
double norm (DOUBLEVECTOR *V)
Function Documentation
double norm (DOUBLEVECTOR * V)
Definition at line 76 of file util_math.c.
References DOUBLEVECTOR::co, and DOUBLEVECTOR::nh.
void tridiag (short a, long r, long c, long nx, DOUBLEVECTOR * diag_inf, DOUBLEVECTOR * diag, DOUBLEVECTOR * diag_sup, DOUBLEVECTOR * b, DOUBLEVECTOR * e)
Definition at line 35 of file util_math.c.
References DOUBLEVECTOR::co, free_doublevector(), new_doublevector(), and t_error().