ASCII/write_ascii.h File Reference
Functions
void write_fluidturtle (char *name, short type, DOUBLEMATRIX *DTM, T_INIT *UV)
void write_grassascii (char *name, short type, DOUBLEMATRIX *DTM, T_INIT *UV)
void write_esriascii (char *name, short type, DOUBLEMATRIX *DTM, T_INIT *UV)
Function Documentation
void write_esriascii (char * name, short type, DOUBLEMATRIX * DTM, T_INIT * UV)
Definition at line 107 of file write_ascii.c.
References ascii_esri, DOUBLEVECTOR::co, DOUBLEMATRIX::co, join_strings(), DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, t_error(), T_INIT::U, and T_INIT::V.
Referenced by write_map().
void write_fluidturtle (char * name, short type, DOUBLEMATRIX * DTM, T_INIT * UV)
Definition at line 29 of file write_ascii.c.
References ascii_ft, DOUBLEVECTOR::co, DOUBLEMATRIX::co, join_strings(), DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, t_fclose(), t_fopen(), T_INIT::U, and T_INIT::V.
Referenced by write_map().
void write_grassascii (char * name, short type, DOUBLEMATRIX * DTM, T_INIT * UV)
Definition at line 66 of file write_ascii.c.
References ascii_grass, DOUBLEVECTOR::co, DOUBLEMATRIX::co, join_strings(), DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, T_INIT::U, and T_INIT::V.
Referenced by write_map().