FLUIDTURTLES/write_dem.h File Reference
Functions
void shortmatrix_dem (SHORTMATRIX *matrix, FLOATVECTOR *U, FLOATVECTOR *V, char *outputname, char *comment, short print)
void shortmatrix_dem3 (SHORTMATRIX *matrix, DOUBLEVECTOR *U, DOUBLEVECTOR *V, char *outputname, char *comment, short print)
void longmatrix_dem (LONGMATRIX *matrix, FLOATVECTOR *U, FLOATVECTOR *V, char *outputname, char *comment, short print)
void intmatrix_dem (INTMATRIX *matrix, FLOATVECTOR *U, FLOATVECTOR *V, char *outputname, char *comment, short print)
void floatmatrix_dem (FLOATMATRIX *matrix, FLOATVECTOR *U, FLOATVECTOR *V, char *outputname, char *comment, short print)
void doublematrix_dem (DOUBLEMATRIX *matrix, FLOATVECTOR *U, FLOATVECTOR *V, char *outputname, char *comment, short print)
void doublematrix_dem3 (DOUBLEMATRIX *matrix, DOUBLEVECTOR *U, DOUBLEVECTOR *V, char *outputname, char *comment, short print)
void doublematrix_control (DOUBLEMATRIX *matrix, char *outputname, char *comment, short print)
void floatvector_dem (FLOATVECTOR *vector, char *outputname, char *comment, short print)
void doublevector_dem (DOUBLEVECTOR *vector, char *outputname, char *comment, short print)
void doubletensor_dem (DOUBLETENSOR *tensor, long layer, DOUBLEVECTOR *U, DOUBLEVECTOR *V, char *outputname, char *comment, short print)
void shortmatrix_dem2 (SHORTMATRIX *matrix, DOUBLEVECTOR *U, DOUBLEVECTOR *V, char *outputname, char *comment, short print)
void longmatrix_dem2 (LONGMATRIX *matrix, DOUBLEVECTOR *U, DOUBLEVECTOR *V, char *outputname, char *comment, short print)
void intmatrix_dem2 (INTMATRIX *matrix, FLOATVECTOR *U, FLOATVECTOR *V, char *outputname, char *comment, short print)
void floatmatrix_dem2 (FLOATMATRIX *matrix, FLOATVECTOR *U, FLOATVECTOR *V, char *outputname, char *comment, short print)
void doublematrix_dem2 (DOUBLEMATRIX *matrix, DOUBLEVECTOR *U, DOUBLEVECTOR *V, char *outputname, char *comment, short print)
Function Documentation
void doublematrix_control (DOUBLEMATRIX * matrix, char * outputname, char * comment, short print)
 Writes a matrix of double to a turtle file
Definition at line 555 of file write_dem.c.
References join_strings(), DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, t_fclose(), t_fopen(), WORKING_DIRECTORY, and write_doublematrix_elements().
void doublematrix_dem (DOUBLEMATRIX * matrix, FLOATVECTOR * U, FLOATVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of double to a DEM turtle file
Definition at line 409 of file write_dem.c.
References join_strings(), DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, t_fclose(), t_fopen(), WORKING_DIRECTORY, write_doublematrix_elements(), and write_floatarray_elements().
Referenced by aggregate().
void doublematrix_dem2 (DOUBLEMATRIX * matrix, DOUBLEVECTOR * U, DOUBLEVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of double to a DEM turtle file
Definition at line 1177 of file write_dem.c.
References DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, t_fclose(), t_fopen(), write_doublearray_elements(), and write_doublematrix_elements().
void doublematrix_dem3 (DOUBLEMATRIX * matrix, DOUBLEVECTOR * U, DOUBLEVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of double to a DEM turtle file
Definition at line 481 of file write_dem.c.
References join_strings(), DOUBLEMATRIX::nch, DOUBLEMATRIX::nrh, t_fclose(), t_fopen(), WORKING_DIRECTORY, write_doublearray_elements(), and write_doublematrix_elements().
void doubletensor_dem (DOUBLETENSOR * tensor, long layer, DOUBLEVECTOR * U, DOUBLEVECTOR * V, char * outputname, char * comment, short print)
 Writes a layer of a 3D double tensor (i.e. a matrix) to a turtle file
Definition at line 761 of file write_dem.c.
References DOUBLEMATRIX::co, DOUBLETENSOR::co, free_doublematrix(), join_strings(), matrix(), DOUBLEMATRIX::nch, DOUBLETENSOR::nch, new_doublematrix(), DOUBLEMATRIX::nrh, DOUBLETENSOR::nrh, t_fclose(), t_fopen(), WORKING_DIRECTORY, write_doublearray_elements(), and write_doublematrix_elements().
void doublevector_dem (DOUBLEVECTOR * vector_dem, char * outputname, char * comment, short print)
 Writes a vector of double to a turtle file
Definition at line 689 of file write_dem.c.
References join_strings(), DOUBLEVECTOR::nh, t_fclose(), t_fopen(), WORKING_DIRECTORY, and write_doublearray_elements().
void floatmatrix_dem (FLOATMATRIX * matrix, FLOATVECTOR * U, FLOATVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of float to a DEM turtle file
Definition at line 329 of file write_dem.c.
References join_strings(), FLOATMATRIX::nch, FLOATMATRIX::nrh, t_fclose(), t_fopen(), WORKING_DIRECTORY, write_floatarray_elements(), and write_floatmatrix_elements().
void floatmatrix_dem2 (FLOATMATRIX * matrix, FLOATVECTOR * U, FLOATVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of float to a DEM turtle file
Definition at line 1099 of file write_dem.c.
References FLOATMATRIX::nch, FLOATMATRIX::nrh, t_fclose(), t_fopen(), write_floatarray_elements(), and write_floatmatrix_elements().
void floatvector_dem (FLOATVECTOR * vector_dem, char * outputname, char * comment, short print)
 Writes a vector of float to a turtle file
Definition at line 621 of file write_dem.c.
References join_strings(), FLOATVECTOR::nh, t_fclose(), t_fopen(), WORKING_DIRECTORY, and write_floatarray_elements().
void intmatrix_dem (INTMATRIX * matrix, FLOATVECTOR * U, FLOATVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of int to a DEM turtle file
Definition at line 253 of file write_dem.c.
References join_strings(), INTMATRIX::nch, INTMATRIX::nrh, t_fclose(), t_fopen(), WORKING_DIRECTORY, write_floatarray_elements(), and write_intmatrix_elements().
void intmatrix_dem2 (INTMATRIX * matrix, FLOATVECTOR * U, FLOATVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of int to a DEM turtle file
Definition at line 1029 of file write_dem.c.
References INTMATRIX::nch, INTMATRIX::nrh, t_fclose(), t_fopen(), write_floatarray_elements(), and write_intmatrix_elements().
void longmatrix_dem (LONGMATRIX * matrix, FLOATVECTOR * U, FLOATVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of long int to a DEM turtle file
Definition at line 177 of file write_dem.c.
References join_strings(), LONGMATRIX::nch, LONGMATRIX::nrh, t_fclose(), t_fopen(), WORKING_DIRECTORY, write_floatarray_elements(), and write_longmatrix_elements().
void longmatrix_dem2 (LONGMATRIX * matrix, DOUBLEVECTOR * U, DOUBLEVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of long int to a DEM turtle file
Definition at line 959 of file write_dem.c.
References LONGMATRIX::nch, LONGMATRIX::nrh, t_fclose(), t_fopen(), write_doublearray_elements(), and write_longmatrix_elements().
void shortmatrix_dem (SHORTMATRIX * matrix, FLOATVECTOR * U, FLOATVECTOR * V, char * outputname, char * comment, short print)
Name: elements_dem
Version: 1.0
Synopsis: void shortmatrix_dem(SHORTMATRIX *matrix, FLOATVECTOR *U, FLOATVECTOR *V,
                    char *outputname, char *comment, short print);
Description: write an array of the specified type on a specified file in the turtle DEM format
Authors & Date: Giacomo Bertoldi, September 2000
FILE: LIBRARIES/GEOMORPHOLOGYLIB/write_dem.h, LIBRARIES/GEOMORPHOLOGYLIB/write_dem.c
Inputs: matrix pointer to the matrix or vector with the data
            U                       pointer to the vector with the header (usually [dx, dy, x0, y0])

            V                       pointer to the vector with novalue (usually [X, NV], where X is -1 if NV is less than the mininmum value of the data,

                                    0 if NV is the 0, 1 if NV is greater than the maximum value of the data)

            outputname      output files name (if is declared a string WORKING_DIRECTORY as extern char, the path not must be specificated)

            comment         a string with comments to write into the file

            print           if print=PRINT the command is executed, if print=NOPRINT the command is skipped
Return: void
See Also: write__
Keywords: turtle file
Examples: APPLICATIONS/HYDROLOGY/geotop/geotop.c
 Writes a matrix of short int to a DEM turtle file
Definition at line 33 of file write_dem.c.
References join_strings(), SHORTMATRIX::nch, SHORTMATRIX::nrh, t_fclose(), t_fopen(), WORKING_DIRECTORY, write_floatarray_elements(), and write_shortmatrix_elements().
void shortmatrix_dem2 (SHORTMATRIX * matrix, DOUBLEVECTOR * U, DOUBLEVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of short int to a DEM turtle file
Definition at line 891 of file write_dem.c.
References SHORTMATRIX::nch, SHORTMATRIX::nrh, t_fclose(), t_fopen(), write_doublearray_elements(), and write_shortmatrix_elements().
void shortmatrix_dem3 (SHORTMATRIX * matrix, DOUBLEVECTOR * U, DOUBLEVECTOR * V, char * outputname, char * comment, short print)
 Writes a matrix of short int to a DEM turtle file
Definition at line 104 of file write_dem.c.
References join_strings(), SHORTMATRIX::nch, SHORTMATRIX::nrh, t_fclose(), t_fopen(), WORKING_DIRECTORY, write_doublearray_elements(), and write_shortmatrix_elements().